<a href="https://colab.research.google.com/github/KWERA/Eulers_Loan_Prediction/blob/main/LOAN_DEFAULT_PREDICTION_CHALLENGE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [83]:
from google.colab import drive
drive.mount ('/content/drive')
import pandas as pd
df1 = pd.read_csv("/content/drive/MyDrive/data/traindemographics.csv")
df2 =pd.read_csv("/content/drive/MyDrive/data/trainperf.csv")
df3 =pd.read_csv("/content/drive/MyDrive/data/trainprevloans.csv")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [84]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4346 entries, 0 to 4345
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   customerid                  4346 non-null   object
 1   birthdate                   4346 non-null   object
 2   bank_account_type           4346 non-null   object
 3   longitude_gps               4346 non-null   float64
 4   latitude_gps                4346 non-null   float64
 5   bank_name_clients           4346 non-null   object
 6   bank_branch_clients         51 non-null     object
 7   employment_status_clients   3698 non-null   object
 8   level_of_education_clients  587 non-null    object
dtypes: float64(2), object(7)
memory usage: 305.7+ KB

In [85]:
df1.head(3)

,customerid,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,bank_branch_clients,employment_status_clients,level_of_education_clients
0,8a858e135cb22031015cbafc76964ebd,1973-10-10 00:00:00.000000,Savings,3.319219,6.528604,GT Bank,NaN,NaN,NaN
1,8a858e275c7ea5ec015c82482d7c3996,1986-01-21 00:00:00.000000,Savings,3.325598,7.119403,Sterling Bank,NaN,Permanent,NaN
2,8a858e5b5bd99460015bdc95cd485634,1987-04-01 00:00:00.000000,Savings,5.746100,5.563174,Fidelity Bank,NaN,NaN,NaN

In [86]:
df1.tail(3)

,customerid,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,bank_branch_clients,employment_status_clients,level_of_education_clients
4343,8a858f4f5b66de3a015b66fc83c61902,1989-09-26 00:00:00.000000,Savings,6.295530,7.092508,GT Bank,NaN,Permanent,NaN
4344,8aaae7a74400b28201441c8b62514150,1985-09-06 00:00:00.000000,Savings,3.354206,6.539070,GT Bank,HEAD OFFICE,Permanent,Primary
4345,8a85896653e2e18b0153e69c1b90265c,1975-06-05 00:00:00.000000,Savings,6.661014,7.472700,UBA,NaN,Permanent,NaN

In [87]:
df1.describe()

       longitude_gps  latitude_gps
count    4346.000000   4346.000000
mean        4.626189      7.251356
std         7.184832      3.055052
min      -118.247009    -33.868818
25%         3.354953      6.470610
50%         3.593302      6.621888
75%         6.545220      7.425052
max       151.209290     71.228069

In [88]:
df1.isnull()

,customerid,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,bank_branch_clients,employment_status_clients,level_of_education_clients
0,False,False,False,False,False,False,True,True,True
1,False,False,False,False,False,False,True,False,True
2,False,False,False,False,False,False,True,True,True
3,False,False,False,False,False,False,True,False,True
4,False,False,False,False,False,False,True,False,True
...,...,...,...,...,...,...,...,...,...
4341,False,False,False,False,False,False,True,False,False
4342,False,False,False,False,False,False,True,True,True
4343,False,False,False,False,False,False,True,False,True
4344,False,False,False,False,False,False,False,False,False
4345,False,False,False,False,False,False,True,False,True

In [89]:
df1.notnull()

,customerid,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,bank_branch_clients,employment_status_clients,level_of_education_clients
0,True,True,True,True,True,True,False,False,False
1,True,True,True,True,True,True,False,True,False
2,True,True,True,True,True,True,False,False,False
3,True,True,True,True,True,True,False,True,False
4,True,True,True,True,True,True,False,True,False
...,...,...,...,...,...,...,...,...,...
4341,True,True,True,True,True,True,False,True,True
4342,True,True,True,True,True,True,False,False,False
4343,True,True,True,True,True,True,False,True,False
4344,True,True,True,True,True,True,True,True,True
4345,True,True,True,True,True,True,False,True,False

In [90]:
df1.head(3)

df1.columns

Index(['customerid', 'birthdate', 'bank_account_type', 'longitude_gps',
       'latitude_gps', 'bank_name_clients', 'bank_branch_clients',
       'employment_status_clients', 'level_of_education_clients'],
      dtype='object')

In [91]:
df1.isnull().sum()

customerid                       0
birthdate                        0
bank_account_type                0
longitude_gps                    0
latitude_gps                     0
bank_name_clients                0
bank_branch_clients           4295
employment_status_clients      648
level_of_education_clients    3759
dtype: int64

In [92]:
df1.notnull().sum()

customerid                    4346
birthdate                     4346
bank_account_type             4346
longitude_gps                 4346
latitude_gps                  4346
bank_name_clients             4346
bank_branch_clients             51
employment_status_clients     3698
level_of_education_clients     587
dtype: int64

In [93]:
df1.head(3)

df1.columns

Index(['customerid', 'birthdate', 'bank_account_type', 'longitude_gps',
       'latitude_gps', 'bank_name_clients', 'bank_branch_clients',
       'employment_status_clients', 'level_of_education_clients'],
      dtype='object')

In [94]:
df1.dtypes

customerid                     object
birthdate                      object
bank_account_type              object
longitude_gps                 float64
latitude_gps                  float64
bank_name_clients              object
bank_branch_clients            object
employment_status_clients      object
level_of_education_clients     object
dtype: object

In [95]:
df1.value_counts()

customerid                        birthdate                   bank_account_type  longitude_gps  latitude_gps  bank_name_clients  bank_branch_clients                                             employment_status_clients  level_of_education_clients
8a1088a0484472eb01484669e3ce4e0b  1989-11-09 00:00:00.000000  Savings            3.351667       6.657019      GT Bank            OJUELEGBA                                                       Permanent                  Primary                       1
8a858f475b8bd761015b8c03cb5920cf  1993-10-26 00:00:00.000000  Savings            3.355625       6.637496      FCMB               AKUTE                                                           Permanent                  Graduate                      1
8a858e885c63d379015c682355b72343  1981-04-02 00:00:00.000000  Savings            3.774967       6.463389      GT Bank            AJOSE ADEOGUN                                                   Permanent                  Graduate                      1
8a858e9f59d692440159da2c60b42106  1985-06-28 00:00:00.000000  Savings            3.362373       6.642125      UBA                AKOWONJO                                                        Permanent                  Graduate                      1
8a858ecc57b9184b0157bd7491b650ec  1978-02-16 00:00:00.000000  Savings            3.525146       6.668493      GT Bank            47 LAGOS ROAD, IKORODU                                          Permanent                  Secondary                     1
8a858eda552adcc201555d5b88396bcf  1987-09-20 00:00:00.000000  Savings            3.423694       6.426184      Diamond Bank       AJOSE ADEOGUN                                                   Permanent                  Secondary                     1
8a858f0d58a18ebc0158a9bf124b5a30  1991-04-28 00:00:00.000000  Savings            3.309237       6.644254      Zenith Bank        MEDICAL ROAD IKEJA                                              Permanent                  Graduate                      1
8a858f265b5c418f015b5c58effa1a88  1980-09-12 00:00:00.000000  Savings            3.357627       6.615629      Skye Bank          OGBA                                                            Permanent                  Graduate                      1
8a858f2f54e28d530154ecdd303004fa  1983-05-08 00:00:00.000000  Savings            3.478483       6.442001      Diamond Bank       LAGOS                                                           Permanent                  Graduate                      1
8a858f2f54e28d530155075d38ad2d84  1990-10-03 00:00:00.000000  Savings            3.324518       6.641067      Access Bank        PLOT 999C DANMOLE STREET, ADEOLA ODEKU, VICTORIA ISLAND, LAGOS  Permanent                  Graduate                      1
8a858f3e589c40610158b48a71b430d3  1984-03-27 00:00:00.000000  Savings            3.343441       6.660074      GT Bank            OREGUN                                                          Permanent                  Graduate                      1
8a858f415ba54724015baa6a28020272  1978-07-25 00:00:00.000000  Savings            3.385872       6.615470      Zenith Bank        APAPA                                                           Permanent                  Graduate                      1
8a858f6a5a8a6734015a8ab389692db3  1979-10-01 00:00:00.000000  Savings            3.191618       6.505456      First Bank         TINCAN                                                          Permanent                  Secondary                     1
8a1a32fc49b632520149c3b8fdf85139  1979-01-29 00:00:00.000000  Savings            3.306388       6.651843      GT Bank            MUSHIN BRANCH                                                   Permanent                  Graduate                      1
8a858f7057b918e40157b93a0b210f37  1981-08-14 00:00:00.000000  Savings            3.261874       6.620796      GT Bank            ALAUSA                                                          Permanent                  Graduate                      1
8a858f8e5986f510015987965aa9183a  1979-07-01 00:00:00.000000  Savings            3.374096       6.599176      Diamond Bank       LADIPO                                                          Permanent                  Secondary                     1
8a858f93572e873c01574753c9513a4e  1988-01-12 00:00:00.000000  Savings            3.490575       6.438789      Diamond Bank       ABEOKUTA                                                        Permanent                  Graduate                      1
8a858fa257d8223c0157f60ebd4d310f  1991-01-14 00:00:00.000000  Savings            3.365234       6.546365      Access Bank        OAU ILE IFE                                                     Permanent                  Graduate                      1
8a858fc959bc56c80159cafe40c76c01  1992-10-22 00:00:00.000000  Current            3.337483       6.504819      Stanbic IBTC       ADENIRAN OGUNSANYA                                              Permanent                  Graduate                      1
8a858fda56562f8f01565f928f516cea  1969-12-29 00:00:00.000000  Savings            3.386796       6.462141      UBA                WHARF ROAD, APAPA                                               Permanent                  Secondary                     1
8a858fdc57b91cfc0157d2d576b01016  1992-09-04 00:00:00.000000  Savings            3.302734       6.651123      GT Bank            OGBA                                                            Student                    Graduate                      1
8a858fe8555f401f01555f4577350080  1989-08-11 00:00:00.000000  Savings            3.910276       7.426621      Access Bank        HERITAGE BANK, DUGBE, IBADAN                                    Permanent                  Graduate                      1
8a858ff9580b881201581f5624ee7a1b  1984-12-21 00:00:00.000000  Savings            3.854555       7.374125      Access Bank        ACCESS BANK PLC, CHALLENGE ROUNDABOUT IBADAN, OYO STATE.        Permanent                  Graduate                      1
8aaae7a74400b28201441c8b62514150  1985-09-06 00:00:00.000000  Savings            3.354206       6.539070      GT Bank            HEAD OFFICE                                                     Permanent                  Primary                       1
8a858e8455f96c1c015603adbb74325e  1975-04-25 00:00:00.000000  Savings            7.939152       4.636685      GT Bank            TRANS AMADI                                                     Permanent                  Post-Graduate                 1
8a858e695775665c01578086c7ef551a  1978-03-28 00:00:00.000000  Savings            3.355767       6.595738      UBA                ILUPEJU                                                         Permanent                  Graduate                      1
8a858e2d5bb55d46015bc6fa50f3384f  1989-08-30 00:00:00.000000  Savings            3.278954       6.645829      GT Bank            OBA AKRAN BERGER PAINT                                          Permanent                  Graduate                      1
8a858e0b5cf4883c015cf56488eb4d41  1976-04-08 00:00:00.000000  Savings            5.627282       6.321753      First Bank         40,SAPELE ROAD ,OPPOSITE DUMAZ JUNCTION BENIN CITY EDO STATE.   Permanent                  Secondary                     1
8a1eb5ba49a682300149c3c068b806c7  1978-11-25 00:00:00.000000  Savings            3.426698       6.423048      First Bank         17, SANUSI FAFUNWA STREET, VICTORIA ISLAND, LAGOS               Permanent                  Secondary                     1
8a2ad9ce4c453e06014c4b3175e52407  1974-09-12 00:00:00.000000  Current            3.339384       6.636486      EcoBank            OGBA                                                            Permanent                  Post-Graduate                 1
8a33a06e4a5075c2014a5295aa0c2224  1977-04-30 00:00:00.000000  Savings            3.232740       6.602252      GT Bank             IDI - ORO MUSHIN                                               Permanent                  Graduate                      1
8a3442825124396701513514dad40fa7  1986-08-07 00:00:00.000000  Other              3.375644       6.555519      First Bank         ADEOLA HOPEWELL                                                 Permanent                  Graduate                      1
8a6b87fe4d56512d014d57af446e7ad0  1972-12-02 00:00:00.000000  Current            3.419578       6.434245      Diamond Bank       LEKKI EPE                                                       Permanent                  Graduate                      1
8a76e7d443e6e97c0143ed0a13cb4f61  1974-02-23 00:00:00.000000  Savings            3.323364       6.606437      GT Bank            GBAGADA                                                         Permanent                  Graduate                      1
8a76e7d443e6e97c0143ed0a33375981  1984-04-18 00:00:00.000000  Savings            3.574784       6.882305      First Bank         OGUDU, OJOTA                                                    Permanent                  Graduate                      1
8a81890b51d31db90151d5fd989c1dbd  1984-06-13 00:00:00.000000  Savings            3.325616       6.653188      Sterling Bank      STERLING BANK PLC 102, IJU ROAD, IFAKO BRANCH                   Permanent                  Graduate                      1
8a81894c529babae0152a10bafeb6895  1983-01-04 00:00:00.000000  Other              3.334007       6.540474      First Bank         MAFOLUKU                                                        Permanent                  Primary                       1
8a85882653e2eb990153e7b4c52d2815  1984-04-17 00:00:00.000000  Other              3.910296       7.439592      GT Bank            OBA ADEBIMPE                                                    Self-Employed              Graduate                      1
8a85886e54beabf90154c0a29ae757c0  1985-08-23 00:00:00.000000  Savings            3.885298       7.320700      GT Bank            DUGBE,IBADAN                                                    Permanent                  Graduate                      1
8a8588ae53f1cb7c015405113ce7447d  1981-08-27 00:00:00.000000  Other              3.873567       7.418831      UBA                DUGBE, IBADAN                                                   Permanent                  Post-Graduate                 1
8a8588dc5384a05f01539d3773865219  1985-05-13 00:00:00.000000  Other              3.870417       7.360579      Diamond Bank       RING ROAD                                                       Permanent                  Graduate                      1
8a8589005384ab570153880ceba74594  1979-03-25 00:00:00.000000  Other              3.415010       6.444252      GT Bank            AWOLOWO                                                         Permanent                  Graduate                      1
8a85890253e2f1180153eae33e5e6bc3  1988-03-08 00:00:00.000000  Savings            3.373518       6.643441      GT Bank            OBA AKRAN ROAD, IKEJA,                                          Permanent                  Graduate                      1
8a85891e53ad0e6b0153b3d3854156fb  1982-02-06 00:00:00.000000  Savings            3.502045       6.621253      UBA                ABULE EGBA U-TURN,BRANCH                                        Permanent                  Graduate                      1
8a85893d53e2e2f30153ea96bf9d09ca  1983-06-15 00:00:00.000000  Savings            6.544435       9.581125      Keystone Bank      BOSSO ROAD, MINNA                                               Permanent                  Graduate                      1
8a85895354be33300154c4e81edf0dd7  1989-11-26 00:00:00.000000  Savings            3.377246       6.587346      Skye Bank          OREGUN                                                          Permanent                  Post-Graduate                 1
8a8589a453bc422d0153c3b0afc75159  1976-09-07 00:00:00.000000  Savings            3.838099       7.402351      GT Bank            AKURE BRANCH                                                    Permanent                  Graduate                      1
8a8589a7545186b10154757067323535  1985-04-26 00:00:00.000000  Savings            3.280841       6.629476      Fidelity Bank      OBA AKRAN                                                       Permanent                  Graduate                      1
8a8589b953bc23f70153ccc3fd3519c7  1977-05-31 00:00:00.000000  Savings            4.523422       7.757938      GT Bank            ABULE EGBA                                                      Permanent                  Graduate                      1
8addcb0645aff34b0145b25fe1616ee0  1980-07-29 00:00:00.000000  Savings            3.346899       6.505031      Diamond Bank       HEAD OFFICE                                                     Permanent                  Primary                       1
Name: count, dtype: int64

In [96]:
df1.shape

(4346, 9)

In [97]:
df1['bank_branch_clients'].value_counts()#  can be dropped ,many missing values and not relevant

bank_branch_clients
OGBA                                                              3
HEAD OFFICE                                                       2
AJOSE ADEOGUN                                                     2
OREGUN                                                            2
APAPA                                                             2
AKOWONJO                                                          1
47 LAGOS ROAD, IKORODU                                            1
OAU ILE IFE                                                       1
RING ROAD                                                         1
PLOT 999C DANMOLE STREET, ADEOLA ODEKU, VICTORIA ISLAND, LAGOS    1
HERITAGE BANK, DUGBE, IBADAN                                      1
ADEOLA HOPEWELL                                                   1
WHARF ROAD, APAPA                                                 1
ILUPEJU                                                           1
LAGOS                                                             1
DUGBE,IBADAN                                                      1
OGUDU, OJOTA                                                      1
GBAGADA                                                           1
LEKKI EPE                                                         1
MAFOLUKU                                                          1
AKURE BRANCH                                                      1
17, SANUSI FAFUNWA STREET, VICTORIA ISLAND, LAGOS                 1
 IDI - ORO MUSHIN                                                 1
OBA AKRAN ROAD, IKEJA,                                            1
40,SAPELE ROAD ,OPPOSITE DUMAZ JUNCTION BENIN CITY EDO STATE.     1
ABULE EGBA U-TURN,BRANCH                                          1
ACCESS BANK PLC, CHALLENGE ROUNDABOUT IBADAN, OYO STATE.          1
AWOLOWO                                                           1
ABULE EGBA                                                        1
ABEOKUTA                                                          1
TRANS AMADI                                                       1
OBA AKRAN BERGER PAINT                                            1
BOSSO ROAD, MINNA                                                 1
DUGBE, IBADAN                                                     1
ALAUSA                                                            1
OJUELEGBA                                                         1
MUSHIN BRANCH                                                     1
AKUTE                                                             1
OBA ADEBIMPE                                                      1
STERLING BANK PLC 102, IJU ROAD, IFAKO BRANCH                     1
MEDICAL ROAD IKEJA                                                1
ADENIRAN OGUNSANYA                                                1
OBA AKRAN                                                         1
LADIPO                                                            1
TINCAN                                                            1
Name: count, dtype: int64

In [98]:
df1['level_of_education_clients'].value_counts() #can be dropped doesnt seem relevant

level_of_education_clients
Graduate         420
Secondary         89
Post-Graduate     68
Primary           10
Name: count, dtype: int64

In [99]:
df1['employment_status_clients'].value_counts()

employment_status_clients
Permanent        3146
Self-Employed     348
Student           142
Unemployed         57
Retired             4
Contract            1
Name: count, dtype: int64

In [100]:
df1['employment_status_clients']=df1['employment_status_clients'].fillna('unknown')

In [105]:
df1.head()

,customerid,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,bank_branch_clients,employment_status_clients,level_of_education_clients
0,8a858e135cb22031015cbafc76964ebd,1973-10-10 00:00:00.000000,Savings,3.319219,6.528604,GT Bank,NaN,unknown,NaN
1,8a858e275c7ea5ec015c82482d7c3996,1986-01-21 00:00:00.000000,Savings,3.325598,7.119403,Sterling Bank,NaN,Permanent,NaN
2,8a858e5b5bd99460015bdc95cd485634,1987-04-01 00:00:00.000000,Savings,5.746100,5.563174,Fidelity Bank,NaN,unknown,NaN
3,8a858efd5ca70688015cabd1f1e94b55,1991-07-19 00:00:00.000000,Savings,3.362850,6.642485,GT Bank,NaN,Permanent,NaN
4,8a858e785acd3412015acd48f4920d04,1982-11-22 00:00:00.000000,Savings,8.455332,11.971410,GT Bank,NaN,Permanent,NaN

dropping irrelevant and columns with several null values

In [107]:
df1.drop("bank_branch_clients",axis=1)

,customerid,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,employment_status_clients,level_of_education_clients
0,8a858e135cb22031015cbafc76964ebd,1973-10-10 00:00:00.000000,Savings,3.319219,6.528604,GT Bank,unknown,NaN
1,8a858e275c7ea5ec015c82482d7c3996,1986-01-21 00:00:00.000000,Savings,3.325598,7.119403,Sterling Bank,Permanent,NaN
2,8a858e5b5bd99460015bdc95cd485634,1987-04-01 00:00:00.000000,Savings,5.746100,5.563174,Fidelity Bank,unknown,NaN
3,8a858efd5ca70688015cabd1f1e94b55,1991-07-19 00:00:00.000000,Savings,3.362850,6.642485,GT Bank,Permanent,NaN
4,8a858e785acd3412015acd48f4920d04,1982-11-22 00:00:00.000000,Savings,8.455332,11.971410,GT Bank,Permanent,NaN
...,...,...,...,...,...,...,...,...
4341,8a858f155554552501555588ca2b3b40,1985-12-13 00:00:00.000000,Other,3.236753,7.030168,Stanbic IBTC,Permanent,Graduate
4342,8a858fc65cf978f4015cf97cee3a02ce,1982-07-01 00:00:00.000000,Savings,7.013750,4.875662,GT Bank,unknown,NaN
4343,8a858f4f5b66de3a015b66fc83c61902,1989-09-26 00:00:00.000000,Savings,6.295530,7.092508,GT Bank,Permanent,NaN
4344,8aaae7a74400b28201441c8b62514150,1985-09-06 00:00:00.000000,Savings,3.354206,6.539070,GT Bank,Permanent,Primary
4345,8a85896653e2e18b0153e69c1b90265c,1975-06-05 00:00:00.000000,Savings,6.661014,7.472700,UBA,Permanent,NaN

In [109]:
df1.columns

Index(['customerid', 'birthdate', 'bank_account_type', 'longitude_gps',
       'latitude_gps', 'bank_name_clients', 'bank_branch_clients',
       'employment_status_clients', 'level_of_education_clients'],
      dtype='object')

In [111]:
df1.drop("level_of_education_clients",axis=1)

,customerid,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,bank_branch_clients,employment_status_clients
0,8a858e135cb22031015cbafc76964ebd,1973-10-10 00:00:00.000000,Savings,3.319219,6.528604,GT Bank,NaN,unknown
1,8a858e275c7ea5ec015c82482d7c3996,1986-01-21 00:00:00.000000,Savings,3.325598,7.119403,Sterling Bank,NaN,Permanent
2,8a858e5b5bd99460015bdc95cd485634,1987-04-01 00:00:00.000000,Savings,5.746100,5.563174,Fidelity Bank,NaN,unknown
3,8a858efd5ca70688015cabd1f1e94b55,1991-07-19 00:00:00.000000,Savings,3.362850,6.642485,GT Bank,NaN,Permanent
4,8a858e785acd3412015acd48f4920d04,1982-11-22 00:00:00.000000,Savings,8.455332,11.971410,GT Bank,NaN,Permanent
...,...,...,...,...,...,...,...,...
4341,8a858f155554552501555588ca2b3b40,1985-12-13 00:00:00.000000,Other,3.236753,7.030168,Stanbic IBTC,NaN,Permanent
4342,8a858fc65cf978f4015cf97cee3a02ce,1982-07-01 00:00:00.000000,Savings,7.013750,4.875662,GT Bank,NaN,unknown
4343,8a858f4f5b66de3a015b66fc83c61902,1989-09-26 00:00:00.000000,Savings,6.295530,7.092508,GT Bank,NaN,Permanent
4344,8aaae7a74400b28201441c8b62514150,1985-09-06 00:00:00.000000,Savings,3.354206,6.539070,GT Bank,HEAD OFFICE,Permanent
4345,8a85896653e2e18b0153e69c1b90265c,1975-06-05 00:00:00.000000,Savings,6.661014,7.472700,UBA,NaN,Permanent

checking for duplicates