<a href="https://colab.research.google.com/github/KWERA/Eulers_Loan_Prediction/blob/main/LOAN_DEFAULT_PREDICTION_CHALLENGE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [147]:
from google.colab import drive
drive.mount ('/content/drive')
import pandas as pd
df1 = pd.read_csv("/content/drive/MyDrive/data/traindemographics.csv")
df2 =pd.read_csv("/content/drive/MyDrive/data/trainperf.csv")
df3 =pd.read_csv("/content/drive/MyDrive/data/trainprevloans.csv")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [148]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4346 entries, 0 to 4345
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   customerid                  4346 non-null   object
 1   birthdate                   4346 non-null   object
 2   bank_account_type           4346 non-null   object
 3   longitude_gps               4346 non-null   float64
 4   latitude_gps                4346 non-null   float64
 5   bank_name_clients           4346 non-null   object
 6   bank_branch_clients         51 non-null     object
 7   employment_status_clients   3698 non-null   object
 8   level_of_education_clients  587 non-null    object
dtypes: float64(2), object(7)
memory usage: 305.7+ KB

In [149]:
df1.head(3)

,customerid,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,bank_branch_clients,employment_status_clients,level_of_education_clients
0,8a858e135cb22031015cbafc76964ebd,1973-10-10 00:00:00.000000,Savings,3.319219,6.528604,GT Bank,NaN,NaN,NaN
1,8a858e275c7ea5ec015c82482d7c3996,1986-01-21 00:00:00.000000,Savings,3.325598,7.119403,Sterling Bank,NaN,Permanent,NaN
2,8a858e5b5bd99460015bdc95cd485634,1987-04-01 00:00:00.000000,Savings,5.746100,5.563174,Fidelity Bank,NaN,NaN,NaN

In [150]:
df1.tail(3)

,customerid,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,bank_branch_clients,employment_status_clients,level_of_education_clients
4343,8a858f4f5b66de3a015b66fc83c61902,1989-09-26 00:00:00.000000,Savings,6.295530,7.092508,GT Bank,NaN,Permanent,NaN
4344,8aaae7a74400b28201441c8b62514150,1985-09-06 00:00:00.000000,Savings,3.354206,6.539070,GT Bank,HEAD OFFICE,Permanent,Primary
4345,8a85896653e2e18b0153e69c1b90265c,1975-06-05 00:00:00.000000,Savings,6.661014,7.472700,UBA,NaN,Permanent,NaN

In [151]:
df1.isnull()

,customerid,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,bank_branch_clients,employment_status_clients,level_of_education_clients
0,False,False,False,False,False,False,True,True,True
1,False,False,False,False,False,False,True,False,True
2,False,False,False,False,False,False,True,True,True
3,False,False,False,False,False,False,True,False,True
4,False,False,False,False,False,False,True,False,True
...,...,...,...,...,...,...,...,...,...
4341,False,False,False,False,False,False,True,False,False
4342,False,False,False,False,False,False,True,True,True
4343,False,False,False,False,False,False,True,False,True
4344,False,False,False,False,False,False,False,False,False
4345,False,False,False,False,False,False,True,False,True

In [152]:
df1.notnull()

,customerid,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,bank_branch_clients,employment_status_clients,level_of_education_clients
0,True,True,True,True,True,True,False,False,False
1,True,True,True,True,True,True,False,True,False
2,True,True,True,True,True,True,False,False,False
3,True,True,True,True,True,True,False,True,False
4,True,True,True,True,True,True,False,True,False
...,...,...,...,...,...,...,...,...,...
4341,True,True,True,True,True,True,False,True,True
4342,True,True,True,True,True,True,False,False,False
4343,True,True,True,True,True,True,False,True,False
4344,True,True,True,True,True,True,True,True,True
4345,True,True,True,True,True,True,False,True,False

In [153]:
df1.head(3)

df1.columns

Index(['customerid', 'birthdate', 'bank_account_type', 'longitude_gps',
       'latitude_gps', 'bank_name_clients', 'bank_branch_clients',
       'employment_status_clients', 'level_of_education_clients'],
      dtype='object')

In [154]:
df1.isnull().sum()

customerid                       0
birthdate                        0
bank_account_type                0
longitude_gps                    0
latitude_gps                     0
bank_name_clients                0
bank_branch_clients           4295
employment_status_clients      648
level_of_education_clients    3759
dtype: int64

In [155]:
df1.notnull().sum()

customerid                    4346
birthdate                     4346
bank_account_type             4346
longitude_gps                 4346
latitude_gps                  4346
bank_name_clients             4346
bank_branch_clients             51
employment_status_clients     3698
level_of_education_clients     587
dtype: int64

In [156]:
df1.head(3)

df1.columns

Index(['customerid', 'birthdate', 'bank_account_type', 'longitude_gps',
       'latitude_gps', 'bank_name_clients', 'bank_branch_clients',
       'employment_status_clients', 'level_of_education_clients'],
      dtype='object')

In [157]:
df1.dtypes

customerid                     object
birthdate                      object
bank_account_type              object
longitude_gps                 float64
latitude_gps                  float64
bank_name_clients              object
bank_branch_clients            object
employment_status_clients      object
level_of_education_clients     object
dtype: object

In [158]:
df1.value_counts()

customerid                        birthdate                   bank_account_type  longitude_gps  latitude_gps  bank_name_clients  bank_branch_clients                                             employment_status_clients  level_of_education_clients
8a1088a0484472eb01484669e3ce4e0b  1989-11-09 00:00:00.000000  Savings            3.351667       6.657019      GT Bank            OJUELEGBA                                                       Permanent                  Primary                       1
8a858f475b8bd761015b8c03cb5920cf  1993-10-26 00:00:00.000000  Savings            3.355625       6.637496      FCMB               AKUTE                                                           Permanent                  Graduate                      1
8a858e885c63d379015c682355b72343  1981-04-02 00:00:00.000000  Savings            3.774967       6.463389      GT Bank            AJOSE ADEOGUN                                                   Permanent                  Graduate                      1
8a858e9f59d692440159da2c60b42106  1985-06-28 00:00:00.000000  Savings            3.362373       6.642125      UBA                AKOWONJO                                                        Permanent                  Graduate                      1
8a858ecc57b9184b0157bd7491b650ec  1978-02-16 00:00:00.000000  Savings            3.525146       6.668493      GT Bank            47 LAGOS ROAD, IKORODU                                          Permanent                  Secondary                     1
8a858eda552adcc201555d5b88396bcf  1987-09-20 00:00:00.000000  Savings            3.423694       6.426184      Diamond Bank       AJOSE ADEOGUN                                                   Permanent                  Secondary                     1
8a858f0d58a18ebc0158a9bf124b5a30  1991-04-28 00:00:00.000000  Savings            3.309237       6.644254      Zenith Bank        MEDICAL ROAD IKEJA                                              Permanent                  Graduate                      1
8a858f265b5c418f015b5c58effa1a88  1980-09-12 00:00:00.000000  Savings            3.357627       6.615629      Skye Bank          OGBA                                                            Permanent                  Graduate                      1
8a858f2f54e28d530154ecdd303004fa  1983-05-08 00:00:00.000000  Savings            3.478483       6.442001      Diamond Bank       LAGOS                                                           Permanent                  Graduate                      1
8a858f2f54e28d530155075d38ad2d84  1990-10-03 00:00:00.000000  Savings            3.324518       6.641067      Access Bank        PLOT 999C DANMOLE STREET, ADEOLA ODEKU, VICTORIA ISLAND, LAGOS  Permanent                  Graduate                      1
8a858f3e589c40610158b48a71b430d3  1984-03-27 00:00:00.000000  Savings            3.343441       6.660074      GT Bank            OREGUN                                                          Permanent                  Graduate                      1
8a858f415ba54724015baa6a28020272  1978-07-25 00:00:00.000000  Savings            3.385872       6.615470      Zenith Bank        APAPA                                                           Permanent                  Graduate                      1
8a858f6a5a8a6734015a8ab389692db3  1979-10-01 00:00:00.000000  Savings            3.191618       6.505456      First Bank         TINCAN                                                          Permanent                  Secondary                     1
8a1a32fc49b632520149c3b8fdf85139  1979-01-29 00:00:00.000000  Savings            3.306388       6.651843      GT Bank            MUSHIN BRANCH                                                   Permanent                  Graduate                      1
8a858f7057b918e40157b93a0b210f37  1981-08-14 00:00:00.000000  Savings            3.261874       6.620796      GT Bank            ALAUSA                                                          Permanent                  Graduate                      1
8a858f8e5986f510015987965aa9183a  1979-07-01 00:00:00.000000  Savings            3.374096       6.599176      Diamond Bank       LADIPO                                                          Permanent                  Secondary                     1
8a858f93572e873c01574753c9513a4e  1988-01-12 00:00:00.000000  Savings            3.490575       6.438789      Diamond Bank       ABEOKUTA                                                        Permanent                  Graduate                      1
8a858fa257d8223c0157f60ebd4d310f  1991-01-14 00:00:00.000000  Savings            3.365234       6.546365      Access Bank        OAU ILE IFE                                                     Permanent                  Graduate                      1
8a858fc959bc56c80159cafe40c76c01  1992-10-22 00:00:00.000000  Current            3.337483       6.504819      Stanbic IBTC       ADENIRAN OGUNSANYA                                              Permanent                  Graduate                      1
8a858fda56562f8f01565f928f516cea  1969-12-29 00:00:00.000000  Savings            3.386796       6.462141      UBA                WHARF ROAD, APAPA                                               Permanent                  Secondary                     1
8a858fdc57b91cfc0157d2d576b01016  1992-09-04 00:00:00.000000  Savings            3.302734       6.651123      GT Bank            OGBA                                                            Student                    Graduate                      1
8a858fe8555f401f01555f4577350080  1989-08-11 00:00:00.000000  Savings            3.910276       7.426621      Access Bank        HERITAGE BANK, DUGBE, IBADAN                                    Permanent                  Graduate                      1
8a858ff9580b881201581f5624ee7a1b  1984-12-21 00:00:00.000000  Savings            3.854555       7.374125      Access Bank        ACCESS BANK PLC, CHALLENGE ROUNDABOUT IBADAN, OYO STATE.        Permanent                  Graduate                      1
8aaae7a74400b28201441c8b62514150  1985-09-06 00:00:00.000000  Savings            3.354206       6.539070      GT Bank            HEAD OFFICE                                                     Permanent                  Primary                       1
8a858e8455f96c1c015603adbb74325e  1975-04-25 00:00:00.000000  Savings            7.939152       4.636685      GT Bank            TRANS AMADI                                                     Permanent                  Post-Graduate                 1
8a858e695775665c01578086c7ef551a  1978-03-28 00:00:00.000000  Savings            3.355767       6.595738      UBA                ILUPEJU                                                         Permanent                  Graduate                      1
8a858e2d5bb55d46015bc6fa50f3384f  1989-08-30 00:00:00.000000  Savings            3.278954       6.645829      GT Bank            OBA AKRAN BERGER PAINT                                          Permanent                  Graduate                      1
8a858e0b5cf4883c015cf56488eb4d41  1976-04-08 00:00:00.000000  Savings            5.627282       6.321753      First Bank         40,SAPELE ROAD ,OPPOSITE DUMAZ JUNCTION BENIN CITY EDO STATE.   Permanent                  Secondary                     1
8a1eb5ba49a682300149c3c068b806c7  1978-11-25 00:00:00.000000  Savings            3.426698       6.423048      First Bank         17, SANUSI FAFUNWA STREET, VICTORIA ISLAND, LAGOS               Permanent                  Secondary                     1
8a2ad9ce4c453e06014c4b3175e52407  1974-09-12 00:00:00.000000  Current            3.339384       6.636486      EcoBank            OGBA                                                            Permanent                  Post-Graduate                 1
8a33a06e4a5075c2014a5295aa0c2224  1977-04-30 00:00:00.000000  Savings            3.232740       6.602252      GT Bank             IDI - ORO MUSHIN                                               Permanent                  Graduate                      1
8a3442825124396701513514dad40fa7  1986-08-07 00:00:00.000000  Other              3.375644       6.555519      First Bank         ADEOLA HOPEWELL                                                 Permanent                  Graduate                      1
8a6b87fe4d56512d014d57af446e7ad0  1972-12-02 00:00:00.000000  Current            3.419578       6.434245      Diamond Bank       LEKKI EPE                                                       Permanent                  Graduate                      1
8a76e7d443e6e97c0143ed0a13cb4f61  1974-02-23 00:00:00.000000  Savings            3.323364       6.606437      GT Bank            GBAGADA                                                         Permanent                  Graduate                      1
8a76e7d443e6e97c0143ed0a33375981  1984-04-18 00:00:00.000000  Savings            3.574784       6.882305      First Bank         OGUDU, OJOTA                                                    Permanent                  Graduate                      1
8a81890b51d31db90151d5fd989c1dbd  1984-06-13 00:00:00.000000  Savings            3.325616       6.653188      Sterling Bank      STERLING BANK PLC 102, IJU ROAD, IFAKO BRANCH                   Permanent                  Graduate                      1
8a81894c529babae0152a10bafeb6895  1983-01-04 00:00:00.000000  Other              3.334007       6.540474      First Bank         MAFOLUKU                                                        Permanent                  Primary                       1
8a85882653e2eb990153e7b4c52d2815  1984-04-17 00:00:00.000000  Other              3.910296       7.439592      GT Bank            OBA ADEBIMPE                                                    Self-Employed              Graduate                      1
8a85886e54beabf90154c0a29ae757c0  1985-08-23 00:00:00.000000  Savings            3.885298       7.320700      GT Bank            DUGBE,IBADAN                                                    Permanent                  Graduate                      1
8a8588ae53f1cb7c015405113ce7447d  1981-08-27 00:00:00.000000  Other              3.873567       7.418831      UBA                DUGBE, IBADAN                                                   Permanent                  Post-Graduate                 1
8a8588dc5384a05f01539d3773865219  1985-05-13 00:00:00.000000  Other              3.870417       7.360579      Diamond Bank       RING ROAD                                                       Permanent                  Graduate                      1
8a8589005384ab570153880ceba74594  1979-03-25 00:00:00.000000  Other              3.415010       6.444252      GT Bank            AWOLOWO                                                         Permanent                  Graduate                      1
8a85890253e2f1180153eae33e5e6bc3  1988-03-08 00:00:00.000000  Savings            3.373518       6.643441      GT Bank            OBA AKRAN ROAD, IKEJA,                                          Permanent                  Graduate                      1
8a85891e53ad0e6b0153b3d3854156fb  1982-02-06 00:00:00.000000  Savings            3.502045       6.621253      UBA                ABULE EGBA U-TURN,BRANCH                                        Permanent                  Graduate                      1
8a85893d53e2e2f30153ea96bf9d09ca  1983-06-15 00:00:00.000000  Savings            6.544435       9.581125      Keystone Bank      BOSSO ROAD, MINNA                                               Permanent                  Graduate                      1
8a85895354be33300154c4e81edf0dd7  1989-11-26 00:00:00.000000  Savings            3.377246       6.587346      Skye Bank          OREGUN                                                          Permanent                  Post-Graduate                 1
8a8589a453bc422d0153c3b0afc75159  1976-09-07 00:00:00.000000  Savings            3.838099       7.402351      GT Bank            AKURE BRANCH                                                    Permanent                  Graduate                      1
8a8589a7545186b10154757067323535  1985-04-26 00:00:00.000000  Savings            3.280841       6.629476      Fidelity Bank      OBA AKRAN                                                       Permanent                  Graduate                      1
8a8589b953bc23f70153ccc3fd3519c7  1977-05-31 00:00:00.000000  Savings            4.523422       7.757938      GT Bank            ABULE EGBA                                                      Permanent                  Graduate                      1
8addcb0645aff34b0145b25fe1616ee0  1980-07-29 00:00:00.000000  Savings            3.346899       6.505031      Diamond Bank       HEAD OFFICE                                                     Permanent                  Primary                       1
Name: count, dtype: int64

In [159]:
df1.shape

(4346, 9)

In [160]:
df1['bank_branch_clients'].value_counts()#  can be dropped ,many missing values and not relevant

bank_branch_clients
OGBA                                                              3
HEAD OFFICE                                                       2
AJOSE ADEOGUN                                                     2
OREGUN                                                            2
APAPA                                                             2
AKOWONJO                                                          1
47 LAGOS ROAD, IKORODU                                            1
OAU ILE IFE                                                       1
RING ROAD                                                         1
PLOT 999C DANMOLE STREET, ADEOLA ODEKU, VICTORIA ISLAND, LAGOS    1
HERITAGE BANK, DUGBE, IBADAN                                      1
ADEOLA HOPEWELL                                                   1
WHARF ROAD, APAPA                                                 1
ILUPEJU                                                           1
LAGOS                                                             1
DUGBE,IBADAN                                                      1
OGUDU, OJOTA                                                      1
GBAGADA                                                           1
LEKKI EPE                                                         1
MAFOLUKU                                                          1
AKURE BRANCH                                                      1
17, SANUSI FAFUNWA STREET, VICTORIA ISLAND, LAGOS                 1
 IDI - ORO MUSHIN                                                 1
OBA AKRAN ROAD, IKEJA,                                            1
40,SAPELE ROAD ,OPPOSITE DUMAZ JUNCTION BENIN CITY EDO STATE.     1
ABULE EGBA U-TURN,BRANCH                                          1
ACCESS BANK PLC, CHALLENGE ROUNDABOUT IBADAN, OYO STATE.          1
AWOLOWO                                                           1
ABULE EGBA                                                        1
ABEOKUTA                                                          1
TRANS AMADI                                                       1
OBA AKRAN BERGER PAINT                                            1
BOSSO ROAD, MINNA                                                 1
DUGBE, IBADAN                                                     1
ALAUSA                                                            1
OJUELEGBA                                                         1
MUSHIN BRANCH                                                     1
AKUTE                                                             1
OBA ADEBIMPE                                                      1
STERLING BANK PLC 102, IJU ROAD, IFAKO BRANCH                     1
MEDICAL ROAD IKEJA                                                1
ADENIRAN OGUNSANYA                                                1
OBA AKRAN                                                         1
LADIPO                                                            1
TINCAN                                                            1
Name: count, dtype: int64

In [161]:
df1['level_of_education_clients'].value_counts() #can be dropped doesnt seem relevant

level_of_education_clients
Graduate         420
Secondary         89
Post-Graduate     68
Primary           10
Name: count, dtype: int64

In [162]:
df1['employment_status_clients'].value_counts()

employment_status_clients
Permanent        3146
Self-Employed     348
Student           142
Unemployed         57
Retired             4
Contract            1
Name: count, dtype: int64

In [163]:
df1['employment_status_clients']=df1['employment_status_clients'].fillna('unknown')

In [164]:
df1.head()

,customerid,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,bank_branch_clients,employment_status_clients,level_of_education_clients
0,8a858e135cb22031015cbafc76964ebd,1973-10-10 00:00:00.000000,Savings,3.319219,6.528604,GT Bank,NaN,unknown,NaN
1,8a858e275c7ea5ec015c82482d7c3996,1986-01-21 00:00:00.000000,Savings,3.325598,7.119403,Sterling Bank,NaN,Permanent,NaN
2,8a858e5b5bd99460015bdc95cd485634,1987-04-01 00:00:00.000000,Savings,5.746100,5.563174,Fidelity Bank,NaN,unknown,NaN
3,8a858efd5ca70688015cabd1f1e94b55,1991-07-19 00:00:00.000000,Savings,3.362850,6.642485,GT Bank,NaN,Permanent,NaN
4,8a858e785acd3412015acd48f4920d04,1982-11-22 00:00:00.000000,Savings,8.455332,11.971410,GT Bank,NaN,Permanent,NaN

dropping irrelevant and columns with several null values

In [165]:
df1.drop("bank_branch_clients",axis=1)

,customerid,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,employment_status_clients,level_of_education_clients
0,8a858e135cb22031015cbafc76964ebd,1973-10-10 00:00:00.000000,Savings,3.319219,6.528604,GT Bank,unknown,NaN
1,8a858e275c7ea5ec015c82482d7c3996,1986-01-21 00:00:00.000000,Savings,3.325598,7.119403,Sterling Bank,Permanent,NaN
2,8a858e5b5bd99460015bdc95cd485634,1987-04-01 00:00:00.000000,Savings,5.746100,5.563174,Fidelity Bank,unknown,NaN
3,8a858efd5ca70688015cabd1f1e94b55,1991-07-19 00:00:00.000000,Savings,3.362850,6.642485,GT Bank,Permanent,NaN
4,8a858e785acd3412015acd48f4920d04,1982-11-22 00:00:00.000000,Savings,8.455332,11.971410,GT Bank,Permanent,NaN
...,...,...,...,...,...,...,...,...
4341,8a858f155554552501555588ca2b3b40,1985-12-13 00:00:00.000000,Other,3.236753,7.030168,Stanbic IBTC,Permanent,Graduate
4342,8a858fc65cf978f4015cf97cee3a02ce,1982-07-01 00:00:00.000000,Savings,7.013750,4.875662,GT Bank,unknown,NaN
4343,8a858f4f5b66de3a015b66fc83c61902,1989-09-26 00:00:00.000000,Savings,6.295530,7.092508,GT Bank,Permanent,NaN
4344,8aaae7a74400b28201441c8b62514150,1985-09-06 00:00:00.000000,Savings,3.354206,6.539070,GT Bank,Permanent,Primary
4345,8a85896653e2e18b0153e69c1b90265c,1975-06-05 00:00:00.000000,Savings,6.661014,7.472700,UBA,Permanent,NaN

In [166]:
df1.columns

Index(['customerid', 'birthdate', 'bank_account_type', 'longitude_gps',
       'latitude_gps', 'bank_name_clients', 'bank_branch_clients',
       'employment_status_clients', 'level_of_education_clients'],
      dtype='object')

In [167]:
df1.drop("level_of_education_clients",axis=1)

,customerid,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,bank_branch_clients,employment_status_clients
0,8a858e135cb22031015cbafc76964ebd,1973-10-10 00:00:00.000000,Savings,3.319219,6.528604,GT Bank,NaN,unknown
1,8a858e275c7ea5ec015c82482d7c3996,1986-01-21 00:00:00.000000,Savings,3.325598,7.119403,Sterling Bank,NaN,Permanent
2,8a858e5b5bd99460015bdc95cd485634,1987-04-01 00:00:00.000000,Savings,5.746100,5.563174,Fidelity Bank,NaN,unknown
3,8a858efd5ca70688015cabd1f1e94b55,1991-07-19 00:00:00.000000,Savings,3.362850,6.642485,GT Bank,NaN,Permanent
4,8a858e785acd3412015acd48f4920d04,1982-11-22 00:00:00.000000,Savings,8.455332,11.971410,GT Bank,NaN,Permanent
...,...,...,...,...,...,...,...,...
4341,8a858f155554552501555588ca2b3b40,1985-12-13 00:00:00.000000,Other,3.236753,7.030168,Stanbic IBTC,NaN,Permanent
4342,8a858fc65cf978f4015cf97cee3a02ce,1982-07-01 00:00:00.000000,Savings,7.013750,4.875662,GT Bank,NaN,unknown
4343,8a858f4f5b66de3a015b66fc83c61902,1989-09-26 00:00:00.000000,Savings,6.295530,7.092508,GT Bank,NaN,Permanent
4344,8aaae7a74400b28201441c8b62514150,1985-09-06 00:00:00.000000,Savings,3.354206,6.539070,GT Bank,HEAD OFFICE,Permanent
4345,8a85896653e2e18b0153e69c1b90265c,1975-06-05 00:00:00.000000,Savings,6.661014,7.472700,UBA,NaN,Permanent

checking for duplicates

In [168]:
df1['customerid'].value_counts()

customerid
8a858fca5c35df2c015c39ad8695343e    2
8a858f9f5679951a01567a5b90644817    2
8a858fe65675195a015679452588279c    2
8a858e625c8d993a015c938f829f77ee    2
8a858f1e5cc4bc81015cc548e1eb5206    2
                                   ..
8a858ff15b5d3f84015b5d6327223863    1
8a858fab5bfd307b015bfd4d5b96114d    1
8a858f6057e2dba50157ee0cb3c55da4    1
8a858fa154daefc00154de1b445805fa    1
8a85896653e2e18b0153e69c1b90265c    1
Name: count, Length: 4334, dtype: int64

In [169]:
df1[df1['customerid']=='8a858fca5c35df2c015c39ad8695343e']

,customerid,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,bank_branch_clients,employment_status_clients,level_of_education_clients
138,8a858fca5c35df2c015c39ad8695343e,1980-11-26 00:00:00.000000,Savings,3.352588,7.211089,GT Bank,NaN,Permanent,NaN
159,8a858fca5c35df2c015c39ad8695343e,1980-11-26 00:00:00.000000,Savings,3.352588,7.211089,GT Bank,NaN,Permanent,NaN

In [170]:
df1[df1['customerid']=='8a858f9f5679951a01567a5b90644817']

,customerid,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,bank_branch_clients,employment_status_clients,level_of_education_clients
3546,8a858f9f5679951a01567a5b90644817,1984-12-17 00:00:00.000000,Savings,4.196662,12.429509,Access Bank,NaN,Permanent,NaN
4286,8a858f9f5679951a01567a5b90644817,1984-12-17 00:00:00.000000,Savings,4.196662,12.429509,Access Bank,NaN,Permanent,NaN

In [171]:
df1.shape

(4346, 9)

In [172]:
df1[df1.duplicated(subset=['customerid', 'birthdate', 'bank_account_type', 'longitude_gps',
       'latitude_gps', 'bank_name_clients', 'bank_branch_clients',
       'employment_status_clients', 'level_of_education_clients'], keep=False)]

,customerid,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,bank_branch_clients,employment_status_clients,level_of_education_clients
138,8a858fca5c35df2c015c39ad8695343e,1980-11-26 00:00:00.000000,Savings,3.352588,7.211089,GT Bank,NaN,Permanent,NaN
159,8a858fca5c35df2c015c39ad8695343e,1980-11-26 00:00:00.000000,Savings,3.352588,7.211089,GT Bank,NaN,Permanent,NaN
272,8a858edd57f790040157ffe9b6ed3fbb,1988-01-18 00:00:00.000000,Other,3.782563,7.171356,First Bank,NaN,Permanent,Secondary
445,8a858e6c5c88d145015c8b9627cd5a48,1979-09-30 00:00:00.000000,Savings,3.367008,6.497313,Sterling Bank,NaN,Permanent,NaN
517,8a858edd57f790040157ffe9b6ed3fbb,1988-01-18 00:00:00.000000,Other,3.782563,7.171356,First Bank,NaN,Permanent,Secondary
750,8a858f965bb63a25015bbf63fd062e2e,1974-02-25 00:00:00.000000,Savings,3.936366,6.817958,Stanbic IBTC,NaN,Permanent,NaN
776,8a858f965bb63a25015bbf63fd062e2e,1974-02-25 00:00:00.000000,Savings,3.936366,6.817958,Stanbic IBTC,NaN,Permanent,NaN
798,8a858fc75cd62882015cdaf2f4311b3f,1975-10-27 00:00:00.000000,Savings,7.437607,9.088935,GT Bank,NaN,Permanent,NaN
1010,8a858fe65675195a015679452588279c,1982-08-01 00:00:00.000000,Savings,7.533646,9.046885,UBA,NaN,Permanent,NaN
1015,8a858fe65675195a015679452588279c,1982-08-01 00:00:00.000000,Savings,7.533646,9.046885,UBA,NaN,Permanent,NaN
1090,8a858e6c5c88d145015c8b9627cd5a48,1979-09-30 00:00:00.000000,Savings,3.367008,6.497313,Sterling Bank,NaN,Permanent,NaN
1188,8a858fc75cd62882015cdaf2f4311b3f,1975-10-27 00:00:00.000000,Savings,7.437607,9.088935,GT Bank,NaN,Permanent,NaN
1338,8a858fe05d421ff4015d4c87d2a21ceb,1983-01-20 00:00:00.000000,Savings,8.526960,12.023015,Skye Bank,NaN,Permanent,NaN
1414,8a858e625c8d993a015c938f829f77ee,1988-12-20 00:00:00.000000,Savings,5.768333,5.561992,First Bank,NaN,Permanent,NaN
1480,8a858fe05d421ff4015d4c87d2a21ceb,1983-01-20 00:00:00.000000,Savings,8.526960,12.023015,Skye Bank,NaN,Permanent,NaN
1520,8a858ec65cc6352b015cc64525ea0763,1985-01-30 00:00:00.000000,Savings,3.845728,7.411737,GT Bank,NaN,Permanent,NaN
1928,8a858e625c8d993a015c938f829f77ee,1988-12-20 00:00:00.000000,Savings,5.768333,5.561992,First Bank,NaN,Permanent,NaN
1996,8a858ec65cc6352b015cc64525ea0763,1985-01-30 00:00:00.000000,Savings,3.845728,7.411737,GT Bank,NaN,Permanent,NaN
3021,8a858f1e5baffcc9015bb02b505f180d,1983-04-06 00:00:00.000000,Savings,6.969350,4.818535,GT Bank,NaN,Permanent,NaN
3546,8a858f9f5679951a01567a5b90644817,1984-12-17 00:00:00.000000,Savings,4.196662,12.429509,Access Bank,NaN,Permanent,NaN
4115,8a858f1e5cc4bc81015cc548e1eb5206,1979-09-15 00:00:00.000000,Savings,6.285242,4.922719,UBA,NaN,Permanent,NaN
4126,8a858f1e5baffcc9015bb02b505f180d,1983-04-06 00:00:00.000000,Savings,6.969350,4.818535,GT Bank,NaN,Permanent,NaN
4266,8a858f1e5cc4bc81015cc548e1eb5206,1979-09-15 00:00:00.000000,Savings,6.285242,4.922719,UBA,NaN,Permanent,NaN
4286,8a858f9f5679951a01567a5b90644817,1984-12-17 00:00:00.000000,Savings,4.196662,12.429509,Access Bank,NaN,Permanent,NaN

In [173]:
df1=df1.drop_duplicates()

In [174]:
df1.shape

(4334, 9)

 Merging longitude_gaps & latitude_gaps

In [175]:
df1.describe()

       longitude_gps  latitude_gps
count    4334.000000   4334.000000
mean        4.624000      7.249975
std         7.194031      3.056594
min      -118.247009    -33.868818
25%         3.354857      6.470610
50%         3.591668      6.621730
75%         6.543691      7.425021
max       151.209290     71.228069

In [176]:
df1['location']=df1['longitude_gps'].astype('str')+df1['latitude_gps'].astype('str')

In [177]:
df1['location'].value_counts()

location
3.41797716.4411578    6
3.4166.4351           3
3.26637816.5212905    2
3.85900877.3511715    2
6.33316934.9476346    2
                     ..
7.0086754.7802117     1
3.26994836.5467152    1
7.01204544.8756519    1
8.53554412.0036084    1
6.6610147.4726999     1
Name: count, Length: 4314, dtype: int64

In [178]:
df1.columns

Index(['customerid', 'birthdate', 'bank_account_type', 'longitude_gps',
       'latitude_gps', 'bank_name_clients', 'bank_branch_clients',
       'employment_status_clients', 'level_of_education_clients', 'location'],
      dtype='object')

In [179]:
df1.head()

,customerid,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,bank_branch_clients,employment_status_clients,level_of_education_clients,location
0,8a858e135cb22031015cbafc76964ebd,1973-10-10 00:00:00.000000,Savings,3.319219,6.528604,GT Bank,NaN,unknown,NaN,3.3192196.5286039
1,8a858e275c7ea5ec015c82482d7c3996,1986-01-21 00:00:00.000000,Savings,3.325598,7.119403,Sterling Bank,NaN,Permanent,NaN,3.32559837.1194033
2,8a858e5b5bd99460015bdc95cd485634,1987-04-01 00:00:00.000000,Savings,5.746100,5.563174,Fidelity Bank,NaN,unknown,NaN,5.74609985.5631737
3,8a858efd5ca70688015cabd1f1e94b55,1991-07-19 00:00:00.000000,Savings,3.362850,6.642485,GT Bank,NaN,Permanent,NaN,3.36284976.6424853
4,8a858e785acd3412015acd48f4920d04,1982-11-22 00:00:00.000000,Savings,8.455332,11.971410,GT Bank,NaN,Permanent,NaN,8.455331711.97141

In [180]:
df1[df1['location']=='3.4166.4351']

,customerid,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,bank_branch_clients,employment_status_clients,level_of_education_clients,location
368,8a858f0056b7cf8e0156b9bfbb2066fd,1977-02-11 00:00:00.000000,Other,3.416,6.4351,GT Bank,NaN,Permanent,Post-Graduate,3.4166.4351
757,8a858f475c7ea023015c7f44743f1d04,1992-10-13 00:00:00.000000,Savings,3.416,6.4351,Access Bank,NaN,Permanent,NaN,3.4166.4351
1156,8a858fda56562f8f01565f8c6f936c46,1992-08-13 00:00:00.000000,Other,3.416,6.4351,GT Bank,NaN,Self-Employed,NaN,3.4166.4351

In [181]:
df1[df1['location']=='3.26637816.5212905']

,customerid,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,bank_branch_clients,employment_status_clients,level_of_education_clients,location
513,8a858f6b570f2de901571b4734224a15,1985-12-28 00:00:00.000000,Other,3.266378,6.521291,Access Bank,NaN,Permanent,NaN,3.26637816.5212905
2452,8a858edb5a70bfe0015a74c641dc0122,1961-10-13 00:00:00.000000,Savings,3.266378,6.521291,Sterling Bank,NaN,unknown,NaN,3.26637816.5212905

In [182]:
df1[df1['location']=='8.455331711.97141']

,customerid,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,bank_branch_clients,employment_status_clients,level_of_education_clients,location
4,8a858e785acd3412015acd48f4920d04,1982-11-22 00:00:00.000000,Savings,8.455332,11.97141,GT Bank,NaN,Permanent,NaN,8.455331711.97141

In [183]:
df1.columns

Index(['customerid', 'birthdate', 'bank_account_type', 'longitude_gps',
       'latitude_gps', 'bank_name_clients', 'bank_branch_clients',
       'employment_status_clients', 'level_of_education_clients', 'location'],
      dtype='object')

In [184]:
df1.shape

(4334, 10)

DF2 EXPLORATION.

In [185]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4368 entries, 0 to 4367
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customerid     4368 non-null   object
 1   systemloanid   4368 non-null   int64
 2   loannumber     4368 non-null   int64
 3   approveddate   4368 non-null   object
 4   creationdate   4368 non-null   object
 5   loanamount     4368 non-null   float64
 6   totaldue       4368 non-null   float64
 7   termdays       4368 non-null   int64
 8   referredby     587 non-null    object
 9   good_bad_flag  4368 non-null   object
dtypes: float64(2), int64(3), object(5)
memory usage: 341.4+ KB

In [186]:
df2.head()

,customerid,systemloanid,loannumber,approveddate,creationdate,loanamount,totaldue,termdays,referredby,good_bad_flag
0,8a2a81a74ce8c05d014cfb32a0da1049,301994762,12,2017-07-25 08:22:56.000000,2017-07-25 07:22:47.000000,30000.0,34500.0,30,NaN,Good
1,8a85886e54beabf90154c0a29ae757c0,301965204,2,2017-07-05 17:04:41.000000,2017-07-05 16:04:18.000000,15000.0,17250.0,30,NaN,Good
2,8a8588f35438fe12015444567666018e,301966580,7,2017-07-06 14:52:57.000000,2017-07-06 13:52:51.000000,20000.0,22250.0,15,NaN,Good
3,8a85890754145ace015429211b513e16,301999343,3,2017-07-27 19:00:41.000000,2017-07-27 18:00:35.000000,10000.0,11500.0,15,NaN,Good
4,8a858970548359cc0154883481981866,301962360,9,2017-07-03 23:42:45.000000,2017-07-03 22:42:39.000000,40000.0,44000.0,30,NaN,Good

In [187]:
df2.shape

(4368, 10)

In [188]:
df2.isnull()

,customerid,systemloanid,loannumber,approveddate,creationdate,loanamount,totaldue,termdays,referredby,good_bad_flag
0,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...
4363,False,False,False,False,False,False,False,False,True,False
4364,False,False,False,False,False,False,False,False,True,False
4365,False,False,False,False,False,False,False,False,True,False
4366,False,False,False,False,False,False,False,False,False,False
4367,False,False,False,False,False,False,False,False,True,False

In [189]:
df2.columns

Index(['customerid', 'systemloanid', 'loannumber', 'approveddate',
       'creationdate', 'loanamount', 'totaldue', 'termdays', 'referredby',
       'good_bad_flag'],
      dtype='object')

In [190]:
df2.describe()

       systemloanid   loannumber    loanamount      totaldue     termdays
count  4.368000e+03  4368.000000   4368.000000   4368.000000  4368.000000
mean   3.019810e+08     5.172390  17809.065934  21257.377679    29.261676
std    1.343115e+04     3.653569  10749.694571  11943.510416    11.512519
min    3.019585e+08     2.000000  10000.000000  10000.000000    15.000000
25%    3.019691e+08     2.000000  10000.000000  13000.000000    30.000000
50%    3.019801e+08     4.000000  10000.000000  13000.000000    30.000000
75%    3.019935e+08     7.000000  20000.000000  24500.000000    30.000000
max    3.020040e+08    27.000000  60000.000000  68100.000000    90.000000

In [191]:
df2.columns

Index(['customerid', 'systemloanid', 'loannumber', 'approveddate',
       'creationdate', 'loanamount', 'totaldue', 'termdays', 'referredby',
       'good_bad_flag'],
      dtype='object')

In [192]:
df2["systemloanid"].value_counts()

systemloanid
301994762    1
301970392    1
302003414    1
301999826    1
301972590    1
            ..
301959319    1
301960124    1
301993159    1
301974283    1
301967124    1
Name: count, Length: 4368, dtype: int64

In [193]:
df2["customerid"].value_counts()

customerid
8a2a81a74ce8c05d014cfb32a0da1049    1
8a858e6c5c88d145015c894de5001cce    1
8a858eaf5b617c94015b61aa95c124b3    1
8a858ea55b58f026015b5c07521824eb    1
8a858e94580afa79015829ebf4d974d1    1
                                   ..
8a858f385b34d285015b352600354046    1
8a858f415686c0ab015691ea91d45900    1
8a858f54589736f40158a6bcd6ac24fb    1
8a858f5c5ad7d927015adb8b97f96be0    1
8a858fd458639fcc015868eb14b542ad    1
Name: count, Length: 4368, dtype: int64

In [194]:
df2["loannumber"].value_counts()

loannumber
2     1393
3      670
4      443
5      326
7      252
6      247
8      220
10     191
9      180
11     113
12     109
13      78
14      50
15      42
16      20
17      15
19       6
22       5
18       3
20       2
27       1
21       1
23       1
Name: count, dtype: int64

In [195]:
df2["systemloanid"].value_counts()

systemloanid
301994762    1
301970392    1
302003414    1
301999826    1
301972590    1
            ..
301959319    1
301960124    1
301993159    1
301974283    1
301967124    1
Name: count, Length: 4368, dtype: int64

In [196]:
df2[df2.duplicated(subset=['customerid', 'systemloanid', 'loannumber', 'approveddate',
       'creationdate', 'loanamount', 'totaldue', 'termdays', 'referredby',
       'good_bad_flag'], keep=False)]

Empty DataFrame
Columns: [customerid, systemloanid, loannumber, approveddate, creationdate, loanamount, totaldue, termdays, referredby, good_bad_flag]
Index: []

In [197]:
df2["referredby"].value_counts()

referredby
8a858fc55b2548dd015b286e452c678c    8
8a858eeb5bb559d3015bb57fa13f10de    3
8a858f965bb63a25015bc2ddf2577416    3
8a858e125b391784015b395fa56243e6    3
8a858e335b806e4d015b807c181d101f    2
                                   ..
8a858fd35b5dfefb015b5f002aa050a3    1
8a858e3d5c3b5122015c43f776bd4a3a    1
8a858f7a5b39a003015b39ca67ab2efb    1
8a858fa359d61dae0159d698bf503d29    1
8a858eda5c8863ff015c9dead65807bb    1
Name: count, Length: 521, dtype: int64

In [198]:
df2.isnull().sum()

customerid          0
systemloanid        0
loannumber          0
approveddate        0
creationdate        0
loanamount          0
totaldue            0
termdays            0
referredby       3781
good_bad_flag       0
dtype: int64

In [199]:
df2.drop('referredby', axis=1)#has many null values

,customerid,systemloanid,loannumber,approveddate,creationdate,loanamount,totaldue,termdays,good_bad_flag
0,8a2a81a74ce8c05d014cfb32a0da1049,301994762,12,2017-07-25 08:22:56.000000,2017-07-25 07:22:47.000000,30000.0,34500.0,30,Good
1,8a85886e54beabf90154c0a29ae757c0,301965204,2,2017-07-05 17:04:41.000000,2017-07-05 16:04:18.000000,15000.0,17250.0,30,Good
2,8a8588f35438fe12015444567666018e,301966580,7,2017-07-06 14:52:57.000000,2017-07-06 13:52:51.000000,20000.0,22250.0,15,Good
3,8a85890754145ace015429211b513e16,301999343,3,2017-07-27 19:00:41.000000,2017-07-27 18:00:35.000000,10000.0,11500.0,15,Good
4,8a858970548359cc0154883481981866,301962360,9,2017-07-03 23:42:45.000000,2017-07-03 22:42:39.000000,40000.0,44000.0,30,Good
...,...,...,...,...,...,...,...,...,...
4363,8a858e6d58b0cc520158beeb14b22a5a,302003163,2,2017-07-30 09:19:42.000000,2017-07-30 08:18:30.000000,10000.0,13000.0,30,Bad
4364,8a858ee85cf400f5015cf44ab1c42d5c,301998967,2,2017-07-27 15:35:47.000000,2017-07-27 14:35:40.000000,10000.0,13000.0,30,Bad
4365,8a858f365b2547f3015b284597147c94,301995576,3,2017-07-25 16:25:57.000000,2017-07-25 15:24:47.000000,10000.0,11500.0,15,Bad
4366,8a858f935ca09667015ca0ee3bc63f51,301977679,2,2017-07-14 13:50:27.000000,2017-07-14 12:50:21.000000,10000.0,13000.0,30,Bad
4367,8a858fd458639fcc015868eb14b542ad,301967124,8,2017-07-06 21:01:06.000000,2017-07-06 20:01:01.000000,30000.0,34500.0,30,Bad

In [200]:
df2.shape

(4368, 10)