In [1]:
import pandas as pd

In [2]:
df1=pd.read_csv('traindemographics.csv')
df2=pd.read_csv('trainprevloans.csv')
df3=pd.read_csv('trainperf.csv')

## EDA for df1

In [3]:
df1.head(3)

df1.columns

Index(['customerid', 'birthdate', 'bank_account_type', 'longitude_gps',
       'latitude_gps', 'bank_name_clients', 'bank_branch_clients',
       'employment_status_clients', 'level_of_education_clients'],
      dtype='object')

In [4]:
df1.isnull().sum()

customerid                       0
birthdate                        0
bank_account_type                0
longitude_gps                    0
latitude_gps                     0
bank_name_clients                0
bank_branch_clients           4295
employment_status_clients      648
level_of_education_clients    3759
dtype: int64

In [5]:
df1['employment_status_clients']=df1['employment_status_clients'].fillna('unknown')

In [6]:
df1['birthdate']=pd.to_datetime(df1['birthdate'],format='%Y-%m-%d')

In [7]:
df1.shape

(4346, 9)

In [8]:
df1['location_merged']=df1['longitude_gps'].astype('str')+df1['latitude_gps'].astype('str')
df1['location_merged'].value_counts()

3.41797716.4411578       6
3.4166.4351              3
6.96934974.8185346       2
3.52285626.6692642       2
3.4348496.4310422        2
                        ..
4.53327497.4901495       1
3.292056.6449565         1
7.5910117.2107067        1
100.619249413.7461285    1
6.6610147.4726999        1
Name: location_merged, Length: 4314, dtype: int64

In [9]:
df1[df1['location_merged']=='3.41797716.4411578'] # cases of people staying in same location

,customerid,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,bank_branch_clients,employment_status_clients,level_of_education_clients,location_merged
1923,8a858f3e5885ffa30158928cad6501c6,1988-03-04,Savings,3.417977,6.441158,UBA,NaN,Permanent,NaN,3.41797716.4411578
2031,8a858fa15908043201592092ba4b5698,1989-10-09,Savings,3.417977,6.441158,First Bank,NaN,Permanent,NaN,3.41797716.4411578
2627,8a858fc75cd62882015cdf944e017b50,1994-02-12,Savings,3.417977,6.441158,GT Bank,NaN,Permanent,NaN,3.41797716.4411578
2679,8a858fd65b80c79a015b80f0ca4d18d8,1976-05-27,Savings,3.417977,6.441158,GT Bank,NaN,Permanent,NaN,3.41797716.4411578
2710,8a85881053bc33670153c65bdb937097,1983-11-17,Savings,3.417977,6.441158,UBA,NaN,Permanent,NaN,3.41797716.4411578
2981,8a858f4b55df0f530155df2ba21c0cc4,1986-02-26,Savings,3.417977,6.441158,Access Bank,NaN,Permanent,Graduate,3.41797716.4411578

In [10]:
df1[df1['location_merged']=='3.4166.4351']

,customerid,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,bank_branch_clients,employment_status_clients,level_of_education_clients,location_merged
368,8a858f0056b7cf8e0156b9bfbb2066fd,1977-02-11,Other,3.416,6.4351,GT Bank,NaN,Permanent,Post-Graduate,3.4166.4351
757,8a858f475c7ea023015c7f44743f1d04,1992-10-13,Savings,3.416,6.4351,Access Bank,NaN,Permanent,NaN,3.4166.4351
1156,8a858fda56562f8f01565f8c6f936c46,1992-08-13,Other,3.416,6.4351,GT Bank,NaN,Self-Employed,NaN,3.4166.4351

In [11]:
4346-3759

587

In [12]:
df1.isnull().sum()

customerid                       0
birthdate                        0
bank_account_type                0
longitude_gps                    0
latitude_gps                     0
bank_name_clients                0
bank_branch_clients           4295
employment_status_clients        0
level_of_education_clients    3759
location_merged                  0
dtype: int64

In [13]:
df1['bank_name_clients'].value_counts()

GT Bank               1598
First Bank             590
Access Bank            432
UBA                    353
Zenith Bank            301
Diamond Bank           282
EcoBank                150
Stanbic IBTC           145
FCMB                   121
Fidelity Bank          103
Skye Bank              102
Sterling Bank           55
Wema Bank               28
Union Bank              23
Heritage Bank           22
Keystone Bank           19
Standard Chartered      15
Unity Bank               7
Name: bank_name_clients, dtype: int64

In [14]:
df1['bank_account_type'].value_counts()

Savings    3425
Other       865
Current      56
Name: bank_account_type, dtype: int64

In [15]:
df1['bank_branch_clients'].value_counts() # doesnt seem relevant, 4295 nulls with only 50 entries

OGBA                                                              3
HEAD OFFICE                                                       2
AJOSE ADEOGUN                                                     2
OREGUN                                                            2
APAPA                                                             2
AKOWONJO                                                          1
47 LAGOS ROAD, IKORODU                                            1
OAU ILE IFE                                                       1
RING ROAD                                                         1
PLOT 999C DANMOLE STREET, ADEOLA ODEKU, VICTORIA ISLAND, LAGOS    1
HERITAGE BANK, DUGBE, IBADAN                                      1
ADEOLA HOPEWELL                                                   1
WHARF ROAD, APAPA                                                 1
ILUPEJU                                                           1
LAGOS                                                             1
DUGBE,IBADAN                                                      1
OGUDU, OJOTA                                                      1
GBAGADA                                                           1
LEKKI EPE                                                         1
MAFOLUKU                                                          1
AKURE BRANCH                                                      1
17, SANUSI FAFUNWA STREET, VICTORIA ISLAND, LAGOS                 1
 IDI - ORO MUSHIN                                                 1
OBA AKRAN ROAD, IKEJA,                                            1
40,SAPELE ROAD ,OPPOSITE DUMAZ JUNCTION BENIN CITY EDO STATE.     1
ABULE EGBA U-TURN,BRANCH                                          1
ACCESS BANK PLC, CHALLENGE ROUNDABOUT IBADAN, OYO STATE.          1
AWOLOWO                                                           1
ABULE EGBA                                                        1
ABEOKUTA                                                          1
TRANS AMADI                                                       1
OBA AKRAN BERGER PAINT                                            1
BOSSO ROAD, MINNA                                                 1
DUGBE, IBADAN                                                     1
ALAUSA                                                            1
OJUELEGBA                                                         1
MUSHIN BRANCH                                                     1
AKUTE                                                             1
OBA ADEBIMPE                                                      1
STERLING BANK PLC 102, IJU ROAD, IFAKO BRANCH                     1
MEDICAL ROAD IKEJA                                                1
ADENIRAN OGUNSANYA                                                1
OBA AKRAN                                                         1
LADIPO                                                            1
TINCAN                                                            1
Name: bank_branch_clients, dtype: int64

In [16]:
df1['employment_status_clients'].value_counts()

Permanent        3146
unknown           648
Self-Employed     348
Student           142
Unemployed         57
Retired             4
Contract            1
Name: employment_status_clients, dtype: int64

In [17]:
df1['level_of_education_clients'].value_counts() #can be dropped has alot of nulls

Graduate         420
Secondary         89
Post-Graduate     68
Primary           10
Name: level_of_education_clients, dtype: int64

In [18]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4346 entries, 0 to 4345
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   customerid                  4346 non-null   object
 1   birthdate                   4346 non-null   datetime64[ns]
 2   bank_account_type           4346 non-null   object
 3   longitude_gps               4346 non-null   float64
 4   latitude_gps                4346 non-null   float64
 5   bank_name_clients           4346 non-null   object
 6   bank_branch_clients         51 non-null     object
 7   employment_status_clients   4346 non-null   object
 8   level_of_education_clients  587 non-null    object
 9   location_merged             4346 non-null   object
dtypes: datetime64[ns](1), float64(2), object(7)
memory usage: 339.7+ KB

In [19]:
df1[df1['customerid']=='8a858fca5c35df2c015c39ad8695343e'] # some customer records appear duplicated

,customerid,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,bank_branch_clients,employment_status_clients,level_of_education_clients,location_merged
138,8a858fca5c35df2c015c39ad8695343e,1980-11-26,Savings,3.352588,7.211089,GT Bank,NaN,Permanent,NaN,3.35258847.2110894
159,8a858fca5c35df2c015c39ad8695343e,1980-11-26,Savings,3.352588,7.211089,GT Bank,NaN,Permanent,NaN,3.35258847.2110894

In [20]:
df1[df1['customerid']=='8a858f9f5679951a01567a5b90644817'] #some customer records appear duplicated

,customerid,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,bank_branch_clients,employment_status_clients,level_of_education_clients,location_merged
3546,8a858f9f5679951a01567a5b90644817,1984-12-17,Savings,4.196662,12.429509,Access Bank,NaN,Permanent,NaN,4.196662212.4295094
4286,8a858f9f5679951a01567a5b90644817,1984-12-17,Savings,4.196662,12.429509,Access Bank,NaN,Permanent,NaN,4.196662212.4295094

In [21]:
df1['customerid'].value_counts()

8a858fca5c35df2c015c39ad8695343e    2
8a858f9f5679951a01567a5b90644817    2
8a858fe65675195a015679452588279c    2
8a858e625c8d993a015c938f829f77ee    2
8a858f1e5cc4bc81015cc548e1eb5206    2
                                   ..
8a858ff15b5d3f84015b5d6327223863    1
8a858fab5bfd307b015bfd4d5b96114d    1
8a858f6057e2dba50157ee0cb3c55da4    1
8a858fa154daefc00154de1b445805fa    1
8a85896653e2e18b0153e69c1b90265c    1
Name: customerid, Length: 4334, dtype: int64

In [22]:
df1.shape

(4346, 10)

In [23]:
df1[df1.duplicated(subset=['customerid', 'birthdate', 'bank_account_type', 'longitude_gps',
       'latitude_gps', 'bank_name_clients', 'bank_branch_clients',
       'employment_status_clients', 'level_of_education_clients'], keep=False)]

,customerid,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,bank_branch_clients,employment_status_clients,level_of_education_clients,location_merged
138,8a858fca5c35df2c015c39ad8695343e,1980-11-26,Savings,3.352588,7.211089,GT Bank,NaN,Permanent,NaN,3.35258847.2110894
159,8a858fca5c35df2c015c39ad8695343e,1980-11-26,Savings,3.352588,7.211089,GT Bank,NaN,Permanent,NaN,3.35258847.2110894
272,8a858edd57f790040157ffe9b6ed3fbb,1988-01-18,Other,3.782563,7.171356,First Bank,NaN,Permanent,Secondary,3.78256257.1713559
445,8a858e6c5c88d145015c8b9627cd5a48,1979-09-30,Savings,3.367008,6.497313,Sterling Bank,NaN,Permanent,NaN,3.36700836.4973131
517,8a858edd57f790040157ffe9b6ed3fbb,1988-01-18,Other,3.782563,7.171356,First Bank,NaN,Permanent,Secondary,3.78256257.1713559
750,8a858f965bb63a25015bbf63fd062e2e,1974-02-25,Savings,3.936366,6.817958,Stanbic IBTC,NaN,Permanent,NaN,3.9363666.8179575
776,8a858f965bb63a25015bbf63fd062e2e,1974-02-25,Savings,3.936366,6.817958,Stanbic IBTC,NaN,Permanent,NaN,3.9363666.8179575
798,8a858fc75cd62882015cdaf2f4311b3f,1975-10-27,Savings,7.437607,9.088935,GT Bank,NaN,Permanent,NaN,7.43760739.0889352
1010,8a858fe65675195a015679452588279c,1982-08-01,Savings,7.533646,9.046885,UBA,NaN,Permanent,NaN,7.53364599.0468853
1015,8a858fe65675195a015679452588279c,1982-08-01,Savings,7.533646,9.046885,UBA,NaN,Permanent,NaN,7.53364599.0468853
1090,8a858e6c5c88d145015c8b9627cd5a48,1979-09-30,Savings,3.367008,6.497313,Sterling Bank,NaN,Permanent,NaN,3.36700836.4973131
1188,8a858fc75cd62882015cdaf2f4311b3f,1975-10-27,Savings,7.437607,9.088935,GT Bank,NaN,Permanent,NaN,7.43760739.0889352
1338,8a858fe05d421ff4015d4c87d2a21ceb,1983-01-20,Savings,8.526960,12.023015,Skye Bank,NaN,Permanent,NaN,8.5269612.023015
1414,8a858e625c8d993a015c938f829f77ee,1988-12-20,Savings,5.768333,5.561992,First Bank,NaN,Permanent,NaN,5.76833335.5619918
1480,8a858fe05d421ff4015d4c87d2a21ceb,1983-01-20,Savings,8.526960,12.023015,Skye Bank,NaN,Permanent,NaN,8.5269612.023015
1520,8a858ec65cc6352b015cc64525ea0763,1985-01-30,Savings,3.845728,7.411737,GT Bank,NaN,Permanent,NaN,3.84572837.4117366
1928,8a858e625c8d993a015c938f829f77ee,1988-12-20,Savings,5.768333,5.561992,First Bank,NaN,Permanent,NaN,5.76833335.5619918
1996,8a858ec65cc6352b015cc64525ea0763,1985-01-30,Savings,3.845728,7.411737,GT Bank,NaN,Permanent,NaN,3.84572837.4117366
3021,8a858f1e5baffcc9015bb02b505f180d,1983-04-06,Savings,6.969350,4.818535,GT Bank,NaN,Permanent,NaN,6.96934974.8185346
3546,8a858f9f5679951a01567a5b90644817,1984-12-17,Savings,4.196662,12.429509,Access Bank,NaN,Permanent,NaN,4.196662212.4295094
4115,8a858f1e5cc4bc81015cc548e1eb5206,1979-09-15,Savings,6.285242,4.922719,UBA,NaN,Permanent,NaN,6.28524164.9227194
4126,8a858f1e5baffcc9015bb02b505f180d,1983-04-06,Savings,6.969350,4.818535,GT Bank,NaN,Permanent,NaN,6.96934974.8185346
4266,8a858f1e5cc4bc81015cc548e1eb5206,1979-09-15,Savings,6.285242,4.922719,UBA,NaN,Permanent,NaN,6.28524164.9227194
4286,8a858f9f5679951a01567a5b90644817,1984-12-17,Savings,4.196662,12.429509,Access Bank,NaN,Permanent,NaN,4.196662212.4295094

In [24]:
df1=df1.drop_duplicates() # dropped 12 duplicates in this dataset ,4346-4334=12
df1.shape

(4334, 10)

In [25]:
#df1.drop('bank_branch_clients', axis=1)
df1.columns

Index(['customerid', 'birthdate', 'bank_account_type', 'longitude_gps',
       'latitude_gps', 'bank_name_clients', 'bank_branch_clients',
       'employment_status_clients', 'level_of_education_clients',
       'location_merged'],
      dtype='object')

In [26]:
df1=df1[['customerid', 'birthdate', 'bank_account_type', 'longitude_gps','latitude_gps', 'bank_name_clients','employment_status_clients','location_merged']]
df1.shape

(4334, 8)

In [27]:
df1[df1['customerid']=='8a858fca5c35df2c015c39ad8695343e'] # duplicates deleted

,customerid,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,employment_status_clients,location_merged
138,8a858fca5c35df2c015c39ad8695343e,1980-11-26,Savings,3.352588,7.211089,GT Bank,Permanent,3.35258847.2110894

In [28]:
df1.isnull().sum()

customerid                   0
birthdate                    0
bank_account_type            0
longitude_gps                0
latitude_gps                 0
bank_name_clients            0
employment_status_clients    0
location_merged              0
dtype: int64

## EDA for df2

In [29]:
df2.head(3)

,customerid,systemloanid,loannumber,approveddate,creationdate,loanamount,totaldue,termdays,closeddate,referredby,firstduedate,firstrepaiddate
0,8a2a81a74ce8c05d014cfb32a0da1049,301682320,2,2016-08-15 18:22:40.000000,2016-08-15 17:22:32.000000,10000.0,13000.0,30,2016-09-01 16:06:48.000000,NaN,2016-09-14 00:00:00.000000,2016-09-01 15:51:43.000000
1,8a2a81a74ce8c05d014cfb32a0da1049,301883808,9,2017-04-28 18:39:07.000000,2017-04-28 17:38:53.000000,10000.0,13000.0,30,2017-05-28 14:44:49.000000,NaN,2017-05-30 00:00:00.000000,2017-05-26 00:00:00.000000
2,8a2a81a74ce8c05d014cfb32a0da1049,301831714,8,2017-03-05 10:56:25.000000,2017-03-05 09:56:19.000000,20000.0,23800.0,30,2017-04-26 22:18:56.000000,NaN,2017-04-04 00:00:00.000000,2017-04-26 22:03:47.000000

In [30]:
df2.shape

(18183, 12)

In [31]:
#df2['firstduedate']=pd.to_datetime(df2['firstduedate'],format='%Y-%m-%d') # converting on column at a time

#converting many columns
date_columns = ['closeddate', 'firstduedate', 'firstrepaiddate']
df2[date_columns]=df2[date_columns].apply(pd.to_datetime,format='%Y-%m-%d')

df2['systemloanid']=df2['systemloanid'].astype('str')

In [32]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18183 entries, 0 to 18182
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customerid       18183 non-null  object
 1   systemloanid     18183 non-null  object
 2   loannumber       18183 non-null  int64
 3   approveddate     18183 non-null  object
 4   creationdate     18183 non-null  object
 5   loanamount       18183 non-null  float64
 6   totaldue         18183 non-null  float64
 7   termdays         18183 non-null  int64
 8   closeddate       18183 non-null  datetime64[ns]
 9   referredby       1026 non-null   object
 10  firstduedate     18183 non-null  datetime64[ns]
 11  firstrepaiddate  18183 non-null  datetime64[ns]
dtypes: datetime64[ns](3), float64(2), int64(2), object(5)
memory usage: 1.7+ MB

In [33]:
df2.isnull().sum()
#referredby has 17157 nulls, only 1026 records

customerid             0
systemloanid           0
loannumber             0
approveddate           0
creationdate           0
loanamount             0
totaldue               0
termdays               0
closeddate             0
referredby         17157
firstduedate           0
firstrepaiddate        0
dtype: int64

In [34]:
df2.describe().T

,count,mean,std,min,25%,50%,75%,max
loannumber,18183.0,4.189353,3.249490,1.0,2.0,3.0,6.0,26.0
loanamount,18183.0,16501.237420,9320.547516,3000.0,10000.0,10000.0,20000.0,60000.0
totaldue,18183.0,19573.202931,10454.245277,3450.0,11500.0,13000.0,24500.0,68100.0
termdays,18183.0,26.692790,10.946556,15.0,15.0,30.0,30.0,90.0

In [35]:
df2.columns

Index(['customerid', 'systemloanid', 'loannumber', 'approveddate',
       'creationdate', 'loanamount', 'totaldue', 'termdays', 'closeddate',
       'referredby', 'firstduedate', 'firstrepaiddate'],
      dtype='object')

In [36]:
filtered_rows = df2[df2['customerid'] == '8a858fe5569398920156a3a9a77b5d02']
sorted_rows = filtered_rows.sort_values(by='loannumber', ascending=True)

# Display the sorted DataFrame
sorted_rows

,customerid,systemloanid,loannumber,approveddate,creationdate,loanamount,totaldue,termdays,closeddate,referredby,firstduedate,firstrepaiddate
16227,8a858fe5569398920156a3a9a77b5d02,301691222,1,2016-08-23 07:07:04.000000,2016-08-23 06:06:56.000000,10000.0,13000.0,30,2016-09-19 20:47:57,NaN,2016-09-22,2016-09-19 20:32:52
13981,8a858fe5569398920156a3a9a77b5d02,301728684,2,2016-09-26 11:44:20.000000,2016-09-26 10:44:11.000000,10000.0,13000.0,30,2016-10-08 15:06:07,NaN,2016-10-26,2016-10-08 14:50:58
13983,8a858fe5569398920156a3a9a77b5d02,301739827,3,2016-10-08 15:56:23.000000,2016-10-08 14:56:14.000000,20000.0,24500.0,30,2016-10-21 08:25:10,NaN,2016-11-07,2016-10-21 08:10:00
9938,8a858fe5569398920156a3a9a77b5d02,301747643,4,2016-10-21 08:55:50.000000,2016-10-21 07:55:40.000000,20000.0,24500.0,30,2016-11-15 11:55:15,NaN,2016-11-21,2016-11-15 11:40:05
9936,8a858fe5569398920156a3a9a77b5d02,301759511,5,2016-11-15 12:58:25.000000,2016-11-15 10:59:51.000000,20000.0,23800.0,30,2016-11-16 07:38:09,NaN,2016-12-15,2016-11-16 07:22:59
10316,8a858fe5569398920156a3a9a77b5d02,301759935,6,2016-11-16 08:41:23.000000,2016-11-16 07:41:13.000000,30000.0,36800.0,60,2016-11-18 12:37:16,NaN,2016-12-16,2016-11-18 12:22:07
16230,8a858fe5569398920156a3a9a77b5d02,301761283,7,2016-11-18 14:48:10.000000,2016-11-18 13:48:00.000000,30000.0,34400.0,30,2016-12-03 13:00:14,NaN,2016-12-19,2016-12-03 12:45:05
13984,8a858fe5569398920156a3a9a77b5d02,301768895,8,2016-12-03 15:04:59.000000,2016-12-03 14:03:44.000000,30000.0,34400.0,30,2016-12-15 21:42:00,NaN,2017-01-02,2016-12-15 21:26:50
16229,8a858fe5569398920156a3a9a77b5d02,301774855,9,2016-12-15 21:45:42.000000,2016-12-15 20:45:31.000000,40000.0,44800.0,30,2016-12-26 12:19:14,NaN,2017-01-16,2016-12-26 12:04:04
10320,8a858fe5569398920156a3a9a77b5d02,301781645,10,2016-12-26 12:36:23.000000,2016-12-26 11:36:12.000000,40000.0,44800.0,30,2016-12-28 19:58:28,NaN,2017-01-25,2016-12-28 19:43:19
9935,8a858fe5569398920156a3a9a77b5d02,301783085,11,2016-12-28 20:01:16.000000,2016-12-28 19:01:05.000000,40000.0,44800.0,30,2016-12-31 09:27:03,NaN,2017-01-27,2016-12-31 09:11:54
10317,8a858fe5569398920156a3a9a77b5d02,301784783,12,2016-12-31 09:30:06.000000,2016-12-31 08:29:55.000000,40000.0,44800.0,30,2017-01-01 05:17:49,NaN,2017-01-30,2017-01-01 05:02:38
9937,8a858fe5569398920156a3a9a77b5d02,301785158,13,2017-01-01 07:29:17.000000,2017-01-01 06:29:05.000000,40000.0,44800.0,30,2017-01-10 12:13:55,NaN,2017-01-31,2017-01-10 11:58:46
10318,8a858fe5569398920156a3a9a77b5d02,301790743,14,2017-01-10 12:17:17.000000,2017-01-10 11:17:09.000000,40000.0,44800.0,30,2017-01-10 12:53:53,NaN,2017-02-09,2017-01-10 12:38:43
13985,8a858fe5569398920156a3a9a77b5d02,301790770,15,2017-01-10 12:58:36.000000,2017-01-10 11:58:24.000000,50000.0,52500.0,30,2017-01-16 11:03:13,NaN,2017-02-09,2017-01-16 10:48:03
13982,8a858fe5569398920156a3a9a77b5d02,301794104,16,2017-01-16 11:08:34.000000,2017-01-16 10:08:25.000000,50000.0,52500.0,30,2017-01-24 16:49:18,NaN,2017-02-15,2017-01-24 16:34:09
9934,8a858fe5569398920156a3a9a77b5d02,301800928,17,2017-01-24 16:55:20.000000,2017-01-24 15:55:11.000000,50000.0,55000.0,60,2017-03-02 14:14:16,NaN,2017-02-23,2017-02-18 16:23:47
10321,8a858fe5569398920156a3a9a77b5d02,301829942,18,2017-03-02 14:28:37.000000,2017-03-02 13:28:28.000000,50000.0,55000.0,60,2017-03-26 03:30:16,NaN,2017-04-03,2017-03-25 15:25:48
10319,8a858fe5569398920156a3a9a77b5d02,301846659,19,2017-03-26 03:34:38.000000,2017-03-26 02:34:21.000000,50000.0,52500.0,30,2017-03-26 07:05:26,NaN,2017-04-25,2017-03-26 06:50:10
16228,8a858fe5569398920156a3a9a77b5d02,301848055,20,2017-03-28 09:06:10.000000,2017-03-28 08:06:01.000000,50000.0,57500.0,90,2017-05-03 10:05:50,NaN,2017-04-27,2017-04-24 19:04:20
16231,8a858fe5569398920156a3a9a77b5d02,301888117,21,2017-05-03 10:17:10.000000,2017-05-03 09:16:58.000000,60000.0,68100.0,90,2017-07-14 13:24:38,NaN,2017-06-02,2017-05-31 01:06:29

In [37]:
df2['referredby'].value_counts() # column to drop

8a858fc55b2548dd015b286e452c678c    14
8a858f965bb63a25015bc2ddf2577416     9
8a858ebb5adce699015adea5d5ae51b3     9
8a8589f35451855401547fc55caa6cd5     8
8a858e025ab3a6c2015ab74cfa5c4431     7
                                    ..
8a858fb959976ce0015998f0a628583b     1
8a858ee65be8d42d015be94e806334fe     1
8a858f5e5cb23c77015cc061b752625b     1
8a858fea5b391cd7015b393aed9e2a04     1
8a858eaa55a0b8ae0155ad2cab5e49cc     1
Name: referredby, Length: 521, dtype: int64

In [38]:
df2['systemloanid'].value_counts() # column to drop

301682320    1
301754669    1
301884544    1
301829670    1
301923724    1
            ..
301607463    1
301836166    1
301609879    1
301899120    1
301715255    1
Name: systemloanid, Length: 18183, dtype: int64

In [39]:
df2['termdays'].value_counts()

30    11045
15     6115
60      993
90       30
Name: termdays, dtype: int64

In [40]:
df2[df2.duplicated(subset=['customerid', 'systemloanid', 'loannumber', 'approveddate',
       'creationdate', 'loanamount', 'totaldue', 'termdays', 'closeddate',
       'referredby', 'firstduedate', 'firstrepaiddate'], keep=False)]
#no duplicated identified

Empty DataFrame
Columns: [customerid, systemloanid, loannumber, approveddate, creationdate, loanamount, totaldue, termdays, closeddate, referredby, firstduedate, firstrepaiddate]
Index: []

In [41]:
df2['loannumber'].value_counts()

1     4344
2     2969
3     2300
4     1860
5     1535
6     1288
7     1036
8      817
9      637
10     446
11     333
12     223
13     146
14      96
15      54
16      33
17      19
18      16
19      10
20       8
21       7
22       2
24       1
23       1
25       1
26       1
Name: loannumber, dtype: int64

In [42]:
df2[df2['loannumber']==22]

,customerid,systemloanid,loannumber,approveddate,creationdate,loanamount,totaldue,termdays,closeddate,referredby,firstduedate,firstrepaiddate
950,8a858f7d5578012a01557ea194d94948,301840987,22,2017-03-18 10:29:08.000000,2017-03-18 09:28:59.000000,50000.0,57500.0,90,2017-06-05 09:56:43,NaN,2017-04-17,2017-04-07 15:27:45
16774,8a858e4456ced8470156d73452f85335,301936806,22,2017-06-13 07:05:01.000000,2017-06-13 06:04:53.000000,60000.0,62700.0,30,2017-07-06 12:15:12,NaN,2017-07-13,2017-07-06 12:05:03

In [43]:
column_to_drop2='referredby'
df2.drop(column_to_drop2,axis=1,inplace=True)
df2.shape

(18183, 11)

# # DF3 EDA

In [44]:
columns_to_convert3 =['approveddate','creationdate']
df3[columns_to_convert3]=df3[columns_to_convert3].apply(pd.to_datetime,format='%Y-%m-%d')

df3['systemloanid']=df3['systemloanid'].astype('str')#df3.head(3)
#df3.shape

In [45]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4368 entries, 0 to 4367
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customerid     4368 non-null   object
 1   systemloanid   4368 non-null   object
 2   loannumber     4368 non-null   int64
 3   approveddate   4368 non-null   datetime64[ns]
 4   creationdate   4368 non-null   datetime64[ns]
 5   loanamount     4368 non-null   float64
 6   totaldue       4368 non-null   float64
 7   termdays       4368 non-null   int64
 8   referredby     587 non-null    object
 9   good_bad_flag  4368 non-null   object
dtypes: datetime64[ns](2), float64(2), int64(2), object(4)
memory usage: 341.4+ KB

In [46]:
df3.describe().T

,count,mean,std,min,25%,50%,75%,max
loannumber,4368.0,5.172390,3.653569,2.0,2.0,4.0,7.0,27.0
loanamount,4368.0,17809.065934,10749.694571,10000.0,10000.0,10000.0,20000.0,60000.0
totaldue,4368.0,21257.377679,11943.510416,10000.0,13000.0,13000.0,24500.0,68100.0
termdays,4368.0,29.261676,11.512519,15.0,30.0,30.0,30.0,90.0

In [47]:
df3['customerid'].value_counts()

8a2a81a74ce8c05d014cfb32a0da1049    1
8a858e6c5c88d145015c894de5001cce    1
8a858eaf5b617c94015b61aa95c124b3    1
8a858ea55b58f026015b5c07521824eb    1
8a858e94580afa79015829ebf4d974d1    1
                                   ..
8a858f385b34d285015b352600354046    1
8a858f415686c0ab015691ea91d45900    1
8a858f54589736f40158a6bcd6ac24fb    1
8a858f5c5ad7d927015adb8b97f96be0    1
8a858fd458639fcc015868eb14b542ad    1
Name: customerid, Length: 4368, dtype: int64

In [48]:
# filtered_rows = df2[df2['customerid'] == '8a858fe5569398920156a3a9a77b5d02']
# sorted_rows = filtered_rows.sort_values(by='loannumber', ascending=True)

# # Display the sorted DataFrame
# sorted_rows

In [50]:
df3['systemloanid'].value_counts()

301994762    1
301970392    1
302003414    1
301999826    1
301972590    1
            ..
301959319    1
301960124    1
301993159    1
301974283    1
301967124    1
Name: systemloanid, Length: 4368, dtype: int64

In [50]:
df3['systemloanid'].value_counts()

301994762    1
301970392    1
302003414    1
301999826    1
301972590    1
            ..
301959319    1
301960124    1
301993159    1
301974283    1
301967124    1
Name: systemloanid, Length: 4368, dtype: int64

In [51]:
df3.isnull().sum()

customerid          0
systemloanid        0
loannumber          0
approveddate        0
creationdate        0
loanamount          0
totaldue            0
termdays            0
referredby       3781
good_bad_flag       0
dtype: int64

In [52]:
df3.shape

(4368, 10)

In [53]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4334 entries, 0 to 4345
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customerid                 4334 non-null   object
 1   birthdate                  4334 non-null   datetime64[ns]
 2   bank_account_type          4334 non-null   object
 3   longitude_gps              4334 non-null   float64
 4   latitude_gps               4334 non-null   float64
 5   bank_name_clients          4334 non-null   object
 6   employment_status_clients  4334 non-null   object
 7   location_merged            4334 non-null   object
dtypes: datetime64[ns](1), float64(2), object(5)
memory usage: 304.7+ KB

In [54]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18183 entries, 0 to 18182
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customerid       18183 non-null  object
 1   systemloanid     18183 non-null  object
 2   loannumber       18183 non-null  int64
 3   approveddate     18183 non-null  object
 4   creationdate     18183 non-null  object
 5   loanamount       18183 non-null  float64
 6   totaldue         18183 non-null  float64
 7   termdays         18183 non-null  int64
 8   closeddate       18183 non-null  datetime64[ns]
 9   firstduedate     18183 non-null  datetime64[ns]
 10  firstrepaiddate  18183 non-null  datetime64[ns]
dtypes: datetime64[ns](3), float64(2), int64(2), object(4)
memory usage: 1.5+ MB

In [55]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4368 entries, 0 to 4367
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customerid     4368 non-null   object
 1   systemloanid   4368 non-null   object
 2   loannumber     4368 non-null   int64
 3   approveddate   4368 non-null   datetime64[ns]
 4   creationdate   4368 non-null   datetime64[ns]
 5   loanamount     4368 non-null   float64
 6   totaldue       4368 non-null   float64
 7   termdays       4368 non-null   int64
 8   referredby     587 non-null    object
 9   good_bad_flag  4368 non-null   object
dtypes: datetime64[ns](2), float64(2), int64(2), object(4)
memory usage: 341.4+ KB

In [56]:
#((4368-3781)/4368)*100 ====13.43% referredby data is provided

In [57]:
column_todrop3='referredby'
df3.drop(column_todrop3,axis=1, inplace=True)

In [58]:
merged_df=df1.merge(df2,on='customerid', how='left')
#merged_df=merged_df.merge(df3,on='customerid', how='left')
merged_df.shape

(14743, 18)

In [59]:
merged_df.head(3)

,customerid,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,employment_status_clients,location_merged,systemloanid,loannumber,approveddate,creationdate,loanamount,totaldue,termdays,closeddate,firstduedate,firstrepaiddate
0,8a858e135cb22031015cbafc76964ebd,1973-10-10,Savings,3.319219,6.528604,GT Bank,unknown,3.3192196.5286039,301943951,1.0,2017-06-19 17:55:26.000000,2017-06-19 16:54:19.000000,10000.0,11500.0,15.0,2017-07-04 18:09:47,2017-07-05,2017-07-04 17:59:36
1,8a858e275c7ea5ec015c82482d7c3996,1986-01-21,Savings,3.325598,7.119403,Sterling Bank,Permanent,3.32559837.1194033,301929966,1.0,2017-06-07 12:47:30.000000,2017-06-07 11:46:22.000000,10000.0,13000.0,30.0,2017-07-10 08:52:54,2017-07-07,2017-07-10 08:42:44
2,8a858e5b5bd99460015bdc95cd485634,1987-04-01,Savings,5.746100,5.563174,Fidelity Bank,unknown,5.74609985.5631737,301931228,3.0,2017-06-08 11:49:34.000000,2017-06-08 10:49:27.000000,10000.0,13000.0,30.0,2017-07-11 10:12:20,2017-07-10,2017-07-11 10:02:11

In [60]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18183 entries, 0 to 18182
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   customerid       18183 non-null  object
 1   systemloanid     18183 non-null  object
 2   loannumber       18183 non-null  int64
 3   approveddate     18183 non-null  object
 4   creationdate     18183 non-null  object
 5   loanamount       18183 non-null  float64
 6   totaldue         18183 non-null  float64
 7   termdays         18183 non-null  int64
 8   closeddate       18183 non-null  datetime64[ns]
 9   firstduedate     18183 non-null  datetime64[ns]
 10  firstrepaiddate  18183 non-null  datetime64[ns]
dtypes: datetime64[ns](3), float64(2), int64(2), object(4)
memory usage: 1.5+ MB

In [61]:
df2[df2['customerid']=='8a858fe5569398920156a3a9a77b5d02'].sort_values(by='loannumber', ascending=True)

,customerid,systemloanid,loannumber,approveddate,creationdate,loanamount,totaldue,termdays,closeddate,firstduedate,firstrepaiddate
16227,8a858fe5569398920156a3a9a77b5d02,301691222,1,2016-08-23 07:07:04.000000,2016-08-23 06:06:56.000000,10000.0,13000.0,30,2016-09-19 20:47:57,2016-09-22,2016-09-19 20:32:52
13981,8a858fe5569398920156a3a9a77b5d02,301728684,2,2016-09-26 11:44:20.000000,2016-09-26 10:44:11.000000,10000.0,13000.0,30,2016-10-08 15:06:07,2016-10-26,2016-10-08 14:50:58
13983,8a858fe5569398920156a3a9a77b5d02,301739827,3,2016-10-08 15:56:23.000000,2016-10-08 14:56:14.000000,20000.0,24500.0,30,2016-10-21 08:25:10,2016-11-07,2016-10-21 08:10:00
9938,8a858fe5569398920156a3a9a77b5d02,301747643,4,2016-10-21 08:55:50.000000,2016-10-21 07:55:40.000000,20000.0,24500.0,30,2016-11-15 11:55:15,2016-11-21,2016-11-15 11:40:05
9936,8a858fe5569398920156a3a9a77b5d02,301759511,5,2016-11-15 12:58:25.000000,2016-11-15 10:59:51.000000,20000.0,23800.0,30,2016-11-16 07:38:09,2016-12-15,2016-11-16 07:22:59
10316,8a858fe5569398920156a3a9a77b5d02,301759935,6,2016-11-16 08:41:23.000000,2016-11-16 07:41:13.000000,30000.0,36800.0,60,2016-11-18 12:37:16,2016-12-16,2016-11-18 12:22:07
16230,8a858fe5569398920156a3a9a77b5d02,301761283,7,2016-11-18 14:48:10.000000,2016-11-18 13:48:00.000000,30000.0,34400.0,30,2016-12-03 13:00:14,2016-12-19,2016-12-03 12:45:05
13984,8a858fe5569398920156a3a9a77b5d02,301768895,8,2016-12-03 15:04:59.000000,2016-12-03 14:03:44.000000,30000.0,34400.0,30,2016-12-15 21:42:00,2017-01-02,2016-12-15 21:26:50
16229,8a858fe5569398920156a3a9a77b5d02,301774855,9,2016-12-15 21:45:42.000000,2016-12-15 20:45:31.000000,40000.0,44800.0,30,2016-12-26 12:19:14,2017-01-16,2016-12-26 12:04:04
10320,8a858fe5569398920156a3a9a77b5d02,301781645,10,2016-12-26 12:36:23.000000,2016-12-26 11:36:12.000000,40000.0,44800.0,30,2016-12-28 19:58:28,2017-01-25,2016-12-28 19:43:19
9935,8a858fe5569398920156a3a9a77b5d02,301783085,11,2016-12-28 20:01:16.000000,2016-12-28 19:01:05.000000,40000.0,44800.0,30,2016-12-31 09:27:03,2017-01-27,2016-12-31 09:11:54
10317,8a858fe5569398920156a3a9a77b5d02,301784783,12,2016-12-31 09:30:06.000000,2016-12-31 08:29:55.000000,40000.0,44800.0,30,2017-01-01 05:17:49,2017-01-30,2017-01-01 05:02:38
9937,8a858fe5569398920156a3a9a77b5d02,301785158,13,2017-01-01 07:29:17.000000,2017-01-01 06:29:05.000000,40000.0,44800.0,30,2017-01-10 12:13:55,2017-01-31,2017-01-10 11:58:46
10318,8a858fe5569398920156a3a9a77b5d02,301790743,14,2017-01-10 12:17:17.000000,2017-01-10 11:17:09.000000,40000.0,44800.0,30,2017-01-10 12:53:53,2017-02-09,2017-01-10 12:38:43
13985,8a858fe5569398920156a3a9a77b5d02,301790770,15,2017-01-10 12:58:36.000000,2017-01-10 11:58:24.000000,50000.0,52500.0,30,2017-01-16 11:03:13,2017-02-09,2017-01-16 10:48:03
13982,8a858fe5569398920156a3a9a77b5d02,301794104,16,2017-01-16 11:08:34.000000,2017-01-16 10:08:25.000000,50000.0,52500.0,30,2017-01-24 16:49:18,2017-02-15,2017-01-24 16:34:09
9934,8a858fe5569398920156a3a9a77b5d02,301800928,17,2017-01-24 16:55:20.000000,2017-01-24 15:55:11.000000,50000.0,55000.0,60,2017-03-02 14:14:16,2017-02-23,2017-02-18 16:23:47
10321,8a858fe5569398920156a3a9a77b5d02,301829942,18,2017-03-02 14:28:37.000000,2017-03-02 13:28:28.000000,50000.0,55000.0,60,2017-03-26 03:30:16,2017-04-03,2017-03-25 15:25:48
10319,8a858fe5569398920156a3a9a77b5d02,301846659,19,2017-03-26 03:34:38.000000,2017-03-26 02:34:21.000000,50000.0,52500.0,30,2017-03-26 07:05:26,2017-04-25,2017-03-26 06:50:10
16228,8a858fe5569398920156a3a9a77b5d02,301848055,20,2017-03-28 09:06:10.000000,2017-03-28 08:06:01.000000,50000.0,57500.0,90,2017-05-03 10:05:50,2017-04-27,2017-04-24 19:04:20
16231,8a858fe5569398920156a3a9a77b5d02,301888117,21,2017-05-03 10:17:10.000000,2017-05-03 09:16:58.000000,60000.0,68100.0,90,2017-07-14 13:24:38,2017-06-02,2017-05-31 01:06:29

In [62]:
merged_df['customerid'].value_counts()

8a858f7d5578012a01557ea194d94948    26
8a858e4456ced8470156d73452f85335    22
8a85886f54517ee0015470749d3c3ce7    21
8a858899538ddb8e0153a780c56e34bb    21
8a858fe5569398920156a3a9a77b5d02    21
                                    ..
8a858f245d1dfd3e015d1e3c6bad1ae8     1
8a858fe8586deed301586e7c59052897     1
8a858f255ca276c5015ca40df7f841ca     1
8a858e775c362114015c3f2c2ab26946     1
8a85896653e2e18b0153e69c1b90265c     1
Name: customerid, Length: 4334, dtype: int64

In [63]:
merged_df.isnull().sum()

customerid                      0
birthdate                       0
bank_account_type               0
longitude_gps                   0
latitude_gps                    0
bank_name_clients               0
employment_status_clients       0
location_merged                 0
systemloanid                 1070
loannumber                   1070
approveddate                 1070
creationdate                 1070
loanamount                   1070
totaldue                     1070
termdays                     1070
closeddate                   1070
firstduedate                 1070
firstrepaiddate              1070
dtype: int64

In [64]:
merged_df.head()

,customerid,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,employment_status_clients,location_merged,systemloanid,loannumber,approveddate,creationdate,loanamount,totaldue,termdays,closeddate,firstduedate,firstrepaiddate
0,8a858e135cb22031015cbafc76964ebd,1973-10-10,Savings,3.319219,6.528604,GT Bank,unknown,3.3192196.5286039,301943951,1.0,2017-06-19 17:55:26.000000,2017-06-19 16:54:19.000000,10000.0,11500.0,15.0,2017-07-04 18:09:47,2017-07-05,2017-07-04 17:59:36
1,8a858e275c7ea5ec015c82482d7c3996,1986-01-21,Savings,3.325598,7.119403,Sterling Bank,Permanent,3.32559837.1194033,301929966,1.0,2017-06-07 12:47:30.000000,2017-06-07 11:46:22.000000,10000.0,13000.0,30.0,2017-07-10 08:52:54,2017-07-07,2017-07-10 08:42:44
2,8a858e5b5bd99460015bdc95cd485634,1987-04-01,Savings,5.746100,5.563174,Fidelity Bank,unknown,5.74609985.5631737,301931228,3.0,2017-06-08 11:49:34.000000,2017-06-08 10:49:27.000000,10000.0,13000.0,30.0,2017-07-11 10:12:20,2017-07-10,2017-07-11 10:02:11
3,8a858e5b5bd99460015bdc95cd485634,1987-04-01,Savings,5.746100,5.563174,Fidelity Bank,unknown,5.74609985.5631737,301895253,1.0,2017-05-08 11:07:01.000000,2017-05-08 10:06:40.000000,10000.0,11500.0,15.0,2017-05-27 13:02:53,2017-05-23,2017-05-27 12:52:45
4,8a858e5b5bd99460015bdc95cd485634,1987-04-01,Savings,5.746100,5.563174,Fidelity Bank,unknown,5.74609985.5631737,301919784,2.0,2017-05-27 17:10:41.000000,2017-05-27 16:10:34.000000,10000.0,11500.0,15.0,2017-06-08 11:13:50,2017-06-12,2017-06-08 11:03:40

In [65]:
merged_df.columns

Index(['customerid', 'birthdate', 'bank_account_type', 'longitude_gps',
       'latitude_gps', 'bank_name_clients', 'employment_status_clients',
       'location_merged', 'systemloanid', 'loannumber', 'approveddate',
       'creationdate', 'loanamount', 'totaldue', 'termdays', 'closeddate',
       'firstduedate', 'firstrepaiddate'],
      dtype='object')

In [66]:
df2['customerid'].value_counts()

8a858f7d5578012a01557ea194d94948    26
8a858e4456ced8470156d73452f85335    22
8a858899538ddb8e0153a780c56e34bb    21
8a85886f54517ee0015470749d3c3ce7    21
8a858fe5569398920156a3a9a77b5d02    21
                                    ..
8a858f7e5c69a6e3015c779b5d6c03b8     1
8a858e165cf9d8e3015d072f06823b83     1
8a858e655b903189015b903875da03da     1
8a858f025bd49f21015bd8590bd83fe8     1
8a858f0656b7820c0156c92ca3ba436f     1
Name: customerid, Length: 4359, dtype: int64

In [68]:
#merged_df[['customerid','systemloanid_x','systemloanid_y']][merged_df['customerid']=='8a858e5b5bd99460015bdc95cd485634']

In [69]:
df2[df2['customerid']=='8a858e5b5bd99460015bdc95cd485634']

,customerid,systemloanid,loannumber,approveddate,creationdate,loanamount,totaldue,termdays,closeddate,firstduedate,firstrepaiddate
2648,8a858e5b5bd99460015bdc95cd485634,301931228,3,2017-06-08 11:49:34.000000,2017-06-08 10:49:27.000000,10000.0,13000.0,30,2017-07-11 10:12:20,2017-07-10,2017-07-11 10:02:11
8520,8a858e5b5bd99460015bdc95cd485634,301895253,1,2017-05-08 11:07:01.000000,2017-05-08 10:06:40.000000,10000.0,11500.0,15,2017-05-27 13:02:53,2017-05-23,2017-05-27 12:52:45
9335,8a858e5b5bd99460015bdc95cd485634,301919784,2,2017-05-27 17:10:41.000000,2017-05-27 16:10:34.000000,10000.0,11500.0,15,2017-06-08 11:13:50,2017-06-12,2017-06-08 11:03:40

In [70]:
df3[df3['customerid']=='8a858e5b5bd99460015bdc95cd485634']

,customerid,systemloanid,loannumber,approveddate,creationdate,loanamount,totaldue,termdays,good_bad_flag
814,8a858e5b5bd99460015bdc95cd485634,301976271,4,2017-07-13 15:40:27,2017-07-13 14:40:19,10000.0,13000.0,30,Good

In [71]:
merged_df[merged_df['customerid']=='8a858e5b5bd99460015bdc95cd485634']

,customerid,birthdate,bank_account_type,longitude_gps,latitude_gps,bank_name_clients,employment_status_clients,location_merged,systemloanid,loannumber,approveddate,creationdate,loanamount,totaldue,termdays,closeddate,firstduedate,firstrepaiddate
2,8a858e5b5bd99460015bdc95cd485634,1987-04-01,Savings,5.7461,5.563174,Fidelity Bank,unknown,5.74609985.5631737,301931228,3.0,2017-06-08 11:49:34.000000,2017-06-08 10:49:27.000000,10000.0,13000.0,30.0,2017-07-11 10:12:20,2017-07-10,2017-07-11 10:02:11
3,8a858e5b5bd99460015bdc95cd485634,1987-04-01,Savings,5.7461,5.563174,Fidelity Bank,unknown,5.74609985.5631737,301895253,1.0,2017-05-08 11:07:01.000000,2017-05-08 10:06:40.000000,10000.0,11500.0,15.0,2017-05-27 13:02:53,2017-05-23,2017-05-27 12:52:45
4,8a858e5b5bd99460015bdc95cd485634,1987-04-01,Savings,5.7461,5.563174,Fidelity Bank,unknown,5.74609985.5631737,301919784,2.0,2017-05-27 17:10:41.000000,2017-05-27 16:10:34.000000,10000.0,11500.0,15.0,2017-06-08 11:13:50,2017-06-12,2017-06-08 11:03:40

In [72]:
#!pip install --upgrade numba

#!pip install ydata-profiling

from ydata_profiling import ProfileReport
# profile = ydata-profiling.ProfileReport(testdemographics)
# profile.to_file(outputfile="../reports/html/testdemographics.html")

In [73]:
profile = ProfileReport(df3)

In [74]:
profile

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]